import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {spawn} from 'node:child_process';
import {AppChanges} from './app-changes.mjs';
function fixture(t){
 const root=fs.mkdtempSync(path.join(os.tmpdir(),'crew-app-draft-unit-')),app=path.join(root,'application'),data=path.join(root,'data');fs.mkdirSync(app);fs.mkdirSync(data);const files=['app.mjs','app.test.mjs','README.md','icon.bin'];
 fs.writeFileSync(path.join(app,'app.mjs'),'export const value=1;\n');fs.writeFileSync(path.join(app,'README.md'),'Original guide\n');fs.writeFileSync(path.join(app,'icon.bin'),Buffer.from([0,1,2]));fs.writeFileSync(path.join(app,'app.test.mjs'),"import test from 'node:test';import assert from 'node:assert/strict';import {value} from './app.mjs';test('reviewed value',()=>assert.equal(value,2));\n");
 const calls=[],proposal={id:'proposal',botId:'a',kind:'app-change',status:'pending',title:'Improve fixture'},store={db:{tasks:[]},bot(id){if(!['a','b'].includes(id))throw Error('Bot not found');return {id};}},learning={get(id){if(id!=='proposal')throw Error('No proposal');return {...proposal};},accept(id){if(id!=='proposal')throw Error('No proposal');proposal.status='reviewed';return {...proposal};}};
 const manager=new AppChanges({appRoot:app,dataRoot:data,store,learning,allowlist:files,spawnProcess(executable,args,options){calls.push({executable,args,options});return spawn(executable,args,options);}});
 t.after(()=>{manager.close();assert.equal(path.dirname(root),path.resolve(os.tmpdir()));assert.match(path.basename(root),/^crew-app-draft-unit-/);fs.rmSync(root,{recursive:true,force:true});});const draft=()=>manager.create({proposalId:'proposal',botId:'a'});
 return {root,app,data,manager,calls,store,draft};
}
test('app drafts copy only approved source and bot edits cannot touch live files or another draft owner',async t=>{
 const f=fixture(t);fs.writeFileSync(path.join(f.app,'private.json'),'fixture private data');assert.throws(()=>f.manager.create({proposalId:'proposal',botId:'b'}),/this bot/);const draft=f.draft(),source=path.join(f.manager.directory(draft.id),'source');assert.equal(fs.existsSync(path.join(source,'private.json')),false);
 f.manager.write({id:draft.id,botId:'a',path:'app.mjs',text:'export const value=2;\n'});assert.equal(fs.readFileSync(path.join(f.app,'app.mjs'),'utf8'),'export const value=1;\n');assert.throws(()=>f.manager.write({id:draft.id,botId:'b',path:'app.mjs',text:'changed'}),/another bot/);
 for(const relative of ['../app.mjs','private.json','icon.bin','source/app.mjs','new.mjs'])assert.throws(()=>f.manager.write({id:draft.id,botId:'a',path:relative,text:'changed'}));assert.equal(f.manager.get(draft.id).changes.length,1);assert.equal(f.calls.length,0);
});
test('automatic syntax checking parses code without executing it',async t=>{
 const f=fixture(t),draft=f.draft(),source=path.join(f.manager.directory(draft.id),'source');f.manager.write({id:draft.id,path:'app.mjs',text:"import fs from 'node:fs';fs.writeFileSync('should-not-exist','executed');export const value=2;\n"});assert.equal((await f.manager.check(draft.id)).passed,true);assert.equal(fs.existsSync(path.join(source,'should-not-exist')),false);assert.deepEqual(f.calls[0].args.slice(0,1),['--check']);
 f.manager.write({id:draft.id,path:'app.mjs',text:'export const value = ;'});assert.equal((await f.manager.check(draft.id)).passed,false);
});
test('test execution needs explicit consent and an exact checked hash; reviewed tests run with restricted files and clean environment',async t=>{
 const f=fixture(t),draft=f.draft();f.manager.write({id:draft.id,path:'app.mjs',text:'export const value=2;\n'});const revision=f.manager.diff(draft.id).reviewHash;await assert.rejects(f.manager.runTests({id:draft.id,reviewHash:revision,testFiles:['app.test.mjs'],confirmed:true}),/syntax checks/);await f.manager.check(draft.id);
 await assert.rejects(f.manager.runTests({id:draft.id,reviewHash:revision,testFiles:['app.test.mjs']}),/explicitly approve/);await assert.rejects(f.manager.runTests({id:draft.id,reviewHash:'stale',testFiles:['app.test.mjs'],confirmed:true}),/exact draft/);
 const result=await f.manager.runTests({id:draft.id,reviewHash:revision,testFiles:['app.test.mjs'],confirmed:true});assert.equal(result.passed,true,result.output);const execution=f.calls.at(-1);assert.ok(execution.args.includes('--permission'));assert.ok(execution.args.includes('--test-isolation=none'));assert.equal(execution.options.shell,undefined);assert.equal(execution.options.windowsHide,true);assert.equal(execution.options.env.OPENAI_API_KEY,undefined);assert.equal(execution.options.env.NODE_OPTIONS,undefined);assert.ok(execution.options.env.CODEX_HOME.endsWith('.crew-test-data'));
});
test('restricted draft tests cannot read files outside the draft or spawn another process',async t=>{
 const f=fixture(t),sentinel=path.join(f.root,'outside-fixture.txt');fs.writeFileSync(sentinel,'read boundary fixture');fs.writeFileSync(path.join(f.app,'app.test.mjs'),"import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {spawnSync} from 'node:child_process';test('restrictions',()=>{assert.throws(()=>fs.readFileSync("+JSON.stringify(sentinel)+"),{code:'ERR_ACCESS_DENIED'});assert.throws(()=>spawnSync(process.execPath,['--version']),{code:'ERR_ACCESS_DENIED'});});");
 const draft=f.draft();f.manager.write({id:draft.id,path:'app.mjs',text:'export const value=2;\n'});await f.manager.check(draft.id);const result=await f.manager.runTests({id:draft.id,reviewHash:f.manager.diff(draft.id).reviewHash,testFiles:['app.test.mjs'],confirmed:true});assert.equal(result.passed,true,result.output);
});
test('apply binds checks/tests/review to unchanged base source and idle tasks, with reversible backups',async t=>{
 const f=fixture(t),draft=f.draft();f.manager.write({id:draft.id,path:'app.mjs',text:'export const value=2;\n'});const revision=f.manager.diff(draft.id).reviewHash;
 assert.throws(()=>f.manager.apply({id:draft.id,reviewHash:revision,confirmed:true}),/passing syntax/);await f.manager.check(draft.id);await f.manager.runTests({id:draft.id,reviewHash:revision,testFiles:['app.test.mjs'],confirmed:true});assert.throws(()=>f.manager.apply({id:draft.id,reviewHash:revision}),/Explicitly approve/);
 f.store.db.tasks.push({status:'queued'});assert.throws(()=>f.manager.apply({id:draft.id,reviewHash:revision,confirmed:true}),/active and queued/);f.store.db.tasks=[];
 fs.writeFileSync(path.join(f.app,'README.md'),'Someone changed the original guide');assert.throws(()=>f.manager.apply({id:draft.id,reviewHash:revision,confirmed:true}),/source changed/);fs.writeFileSync(path.join(f.app,'README.md'),'Original guide\n');
 assert.equal(f.manager.apply({id:draft.id,reviewHash:revision,confirmed:true}).restartRequired,true);assert.equal(f.manager.learning.get('proposal').status,'reviewed');assert.equal(fs.readFileSync(path.join(f.app,'app.mjs'),'utf8'),'export const value=2;\n');assert.throws(()=>f.manager.undo({id:draft.id}),/Explicitly approve/);assert.equal(f.manager.undo({id:draft.id,confirmed:true}).status,'restored');assert.equal(fs.readFileSync(path.join(f.app,'app.mjs'),'utf8'),'export const value=1;\n');
});
test('a changed draft invalidates old checks and a later app edit blocks unsafe undo',async t=>{
 const f=fixture(t),draft=f.draft();f.manager.write({id:draft.id,path:'app.mjs',text:'export const value=2;\n'});await f.manager.check(draft.id);let revision=f.manager.diff(draft.id).reviewHash;await f.manager.runTests({id:draft.id,reviewHash:revision,testFiles:['app.test.mjs'],confirmed:true});f.manager.write({id:draft.id,path:'README.md',text:'Updated guide\n'});assert.throws(()=>f.manager.apply({id:draft.id,reviewHash:revision,confirmed:true}),/exact draft/);
 await f.manager.check(draft.id);revision=f.manager.diff(draft.id).reviewHash;await f.manager.runTests({id:draft.id,reviewHash:revision,testFiles:['app.test.mjs'],confirmed:true});f.manager.apply({id:draft.id,reviewHash:revision,confirmed:true});fs.writeFileSync(path.join(f.app,'app.mjs'),'export const value=3;\n');assert.throws(()=>f.manager.undo({id:draft.id,confirmed:true}),/changed again/);assert.equal(fs.readFileSync(path.join(f.app,'app.mjs'),'utf8'),'export const value=3;\n');
});
test('draft source links are rejected and failed creation leaves no broken draft entry',async t=>{
 const f=fixture(t);f.manager.allowlist.push('missing-file.md');assert.throws(()=>f.draft());assert.deepEqual(f.manager.list(),[]);f.manager.allowlist.pop();const draft=f.draft(),folder=f.manager.directory(draft.id);fs.renameSync(path.join(folder,'source'),path.join(folder,'source-original'));fs.symlinkSync(f.app,path.join(folder,'source'),'junction');assert.throws(()=>f.manager.read({id:draft.id,path:'app.mjs'}),/symbolic/);
});
test('tests that change reviewed source cannot certify the changed draft',async t=>{
 const f=fixture(t);fs.writeFileSync(path.join(f.app,'app.test.mjs'),"import test from 'node:test';import fs from 'node:fs';test('changes source',()=>fs.writeFileSync('app.mjs','export const value=99;'));");const draft=f.draft();f.manager.write({id:draft.id,path:'app.mjs',text:'export const value=2;\n'});await f.manager.check(draft.id);const reviewHash=f.manager.diff(draft.id).reviewHash,result=await f.manager.runTests({id:draft.id,reviewHash,testFiles:['app.test.mjs'],confirmed:true});assert.equal(result.passed,false);assert.match(result.output,/changed during/);assert.throws(()=>f.manager.apply({id:draft.id,reviewHash,confirmed:true}),/exact draft/);
});
test('a partial apply failure restores all files already replaced',async t=>{
 const f=fixture(t),draft=f.draft();f.manager.write({id:draft.id,path:'app.mjs',text:'export const value=2;\n'});f.manager.write({id:draft.id,path:'README.md',text:'Changed guide\n'});await f.manager.check(draft.id);const reviewHash=f.manager.diff(draft.id).reviewHash;await f.manager.runTests({id:draft.id,reviewHash,testFiles:['app.test.mjs'],confirmed:true});
 const rename=fs.renameSync;let once=true;fs.renameSync=(from,to)=>{if(once&&to===path.join(f.app,'app.mjs')){once=false;throw Error('Fixture write failure');}return rename(from,to);};
 try{assert.throws(()=>f.manager.apply({id:draft.id,reviewHash,confirmed:true}),/original files were restored/);}finally{fs.renameSync=rename;}
 assert.equal(fs.readFileSync(path.join(f.app,'app.mjs'),'utf8'),'export const value=1;\n');assert.equal(fs.readFileSync(path.join(f.app,'README.md'),'utf8'),'Original guide\n');assert.equal(f.manager.get(draft.id).status,'rolled-back');
});
test('untracked source junctions and hard links are refused before any syntax process starts',async t=>{
 for(const type of ['junction','hardlink']){const f=fixture(t),draft=f.draft();f.manager.write({id:draft.id,path:'app.mjs',text:'export const value=2;\n'});const source=path.join(f.manager.directory(draft.id),'source'),outside=path.join(f.root,'outside');fs.mkdirSync(outside);fs.writeFileSync(path.join(outside,'fixture.txt'),'harmless outside fixture');if(type==='junction')fs.symlinkSync(outside,path.join(source,'extra-link'),'junction');else fs.linkSync(path.join(outside,'fixture.txt'),path.join(source,'extra-link.txt'));await assert.rejects(f.manager.check(draft.id),/symbolic links, junctions, or hard links/);assert.equal(f.calls.length,0);}
});
test('a linked private temporary folder stops selected tests before launching a process',async t=>{
 const f=fixture(t),draft=f.draft();f.manager.write({id:draft.id,path:'app.mjs',text:'export const value=2;\n'});await f.manager.check(draft.id);const before=f.calls.length,source=path.join(f.manager.directory(draft.id),'source'),temporary=path.join(source,'.crew-test-data'),outside=path.join(f.root,'outside');fs.mkdirSync(outside);fs.rmdirSync(temporary);fs.symlinkSync(outside,temporary,'junction');await assert.rejects(f.manager.runTests({id:draft.id,reviewHash:f.manager.diff(draft.id).reviewHash,testFiles:['app.test.mjs'],confirmed:true}),/symbolic links, junctions, or hard links/);assert.equal(f.calls.length,before);assert.deepEqual(fs.readdirSync(outside),[]);
});
test('an existing nested backup junction blocks apply before copying or replacing files',async t=>{
 const f=fixture(t),draft=f.draft();f.manager.write({id:draft.id,path:'app.mjs',text:'export const value=2;\n'});await f.manager.check(draft.id);const reviewHash=f.manager.diff(draft.id).reviewHash;await f.manager.runTests({id:draft.id,reviewHash,testFiles:['app.test.mjs'],confirmed:true});const backup=path.join(f.manager.directory(draft.id),'backup'),outside=path.join(f.root,'outside');fs.mkdirSync(backup);fs.mkdirSync(outside);fs.symlinkSync(outside,path.join(backup,'nested'),'junction');assert.throws(()=>f.manager.apply({id:draft.id,reviewHash,confirmed:true}),/symbolic links, junctions, or hard links/);assert.deepEqual(fs.readdirSync(outside),[]);assert.equal(fs.readFileSync(path.join(f.app,'app.mjs'),'utf8'),'export const value=1;\n');
});
test('a separate Learning write failure keeps app files committed and reports review still needed without reapplying',async t=>{
 const f=fixture(t),draft=f.draft();f.manager.write({id:draft.id,path:'app.mjs',text:'export const value=2;\n'});await f.manager.check(draft.id);const reviewHash=f.manager.diff(draft.id).reviewHash;await f.manager.runTests({id:draft.id,reviewHash,testFiles:['app.test.mjs'],confirmed:true});const accept=f.manager.learning.accept;let attempts=0;f.manager.learning.accept=()=>{attempts++;throw Error('Fixture Learning write failure');};const result=f.manager.apply({id:draft.id,reviewHash,confirmed:true});assert.equal(result.status,'applied');assert.match(result.reviewWarning,/do not apply these files again/);assert.equal(f.manager.metadata(draft.id).status,'applied');assert.equal(fs.readFileSync(path.join(f.app,'app.mjs'),'utf8'),'export const value=2;\n');assert.throws(()=>f.manager.apply({id:draft.id,reviewHash,confirmed:true}),/exact draft/);assert.equal(attempts,1);assert.match(f.manager.get(draft.id).reviewWarning,/Learning/);f.manager.learning.accept=accept;f.manager.learning.accept('proposal');assert.equal(f.manager.get(draft.id).reviewWarning,'');assert.equal(f.manager.get(draft.id).status,'applied');assert.equal(fs.readFileSync(path.join(f.app,'app.mjs'),'utf8'),'export const value=2;\n');
});
