const PREFIX='folklet.drafts.v1:',TTL=7*86400000,MAX_BYTES=512000;
const valid=value=>typeof value==='string'&&/^[a-zA-Z0-9_-]{1,100}$/.test(value);
export class DraftStorage{
 constructor({storage,now=Date.now}={}){this.storage=storage;this.now=now;this.workspace=null;this.error='';this.saved=new Map();}
 bind(workspace){if(!valid(workspace))throw Error('Invalid draft workspace.');if(this.workspace!==workspace)this.saved.clear();this.workspace=workspace;}
 key(){if(!this.workspace)throw Error('Connect to your workspace first.');return PREFIX+this.workspace;}
 enabled(){try{return this.storage.getItem(this.key()+':enabled')==='yes';}catch{return false;}}
 enable(value){try{if(value)this.storage.setItem(this.key()+':enabled','yes');else{this.storage.removeItem(this.key());this.storage.removeItem(this.key()+':enabled');this.saved.clear();}this.error='';}catch{this.error='This browser could not save draft settings.';throw Error(this.error);}}
 load(){if(!this.enabled())return {drafts:{},attachments:{}};try{const saved=JSON.parse(this.storage.getItem(this.key())||'{}'),drafts={},attachments={};for(const item of Array.isArray(saved.items)?saved.items.slice(-30):[]){if(!valid(item.id)||!Number.isFinite(item.at)||item.at>this.now()+60000||this.now()-item.at>TTL)continue;if(typeof item.text!=='string'||item.text.length>60000)continue;const files=this.files(item.files);this.saved.set(item.id,{...item,files});Object.defineProperty(drafts,item.id,{value:item.text,enumerable:true,writable:true,configurable:true});Object.defineProperty(attachments,item.id,{value:files,enumerable:true,writable:true,configurable:true});}return {drafts,attachments};}catch{this.error='Saved drafts could not be read. Keep any open draft before clearing browser storage.';return {drafts:{},attachments:{}};}}
 files(files){return (Array.isArray(files)?files:[]).slice(0,20).filter(f=>f&&valid(f.owner)&&typeof f.path==='string'&&f.path.length<600&&!f.path.split('/').some(p=>!p||p==='.'||p==='..')&&!/[\\:\x00-\x1f]/.test(f.path)).map(f=>({owner:f.owner,path:f.path}));}
 save(drafts,attachments){if(!this.enabled())return;try{const items=Object.entries(drafts).filter(([id,text])=>valid(id)&&typeof text==='string'&&(text||attachments[id]?.length)).map(([id,text])=>{text=text.slice(0,60000);const files=this.files(attachments[id]),old=this.saved.get(id);return {id,text,files,at:old&&old.text===text&&JSON.stringify(old.files)===JSON.stringify(files)?old.at:this.now()};}).filter(item=>this.now()-item.at<=TTL).sort((a,b)=>a.at-b.at).slice(-30);const value=JSON.stringify({version:1,items});if(new TextEncoder().encode(value).length>MAX_BYTES)throw Error();this.storage.setItem(this.key(),value);for(const item of items)this.saved.set(item.id,item);this.error='';}catch{this.error='Draft autosave failed or exceeded 512 KB. Copy your open draft before closing.';}}
 clear(){this.storage.removeItem(this.key());this.saved.clear();this.error='';}
}
