const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const hostingSteps=[
  {title:'Choose a private host',intro:'Use a spare computer, or a Linux server that stays on when your laptop is off.',body:'For the included setup, choose Ubuntu 24.04 x64 with a regular SSH user. Start around 4 GB RAM for light API work; browsers may need 8 GB or more. This is a planning estimate. A bare server runs browser tools but has no desktop to control.',note:'Buy directly from your provider. Check current prices, backups and traffic charges. Folklet does not order a server or include model credits.',links:true},
  {title:'Install the background service',intro:'On the server, extract a reviewed Folklet source download and open that folder in your SSH session.',body:'The first command installs the pinned runtime. The preview checks the service files before installation. The final command starts Folklet and enables the service.',command:'sh Setup.sh --skip-browser\nsh hosting/install-user-service.sh --dry-run\nsh hosting/install-user-service.sh\nsystemctl --user enable --now crew.service',note:'Use a regular account, without sudo. A new server starts a separate workspace; your laptop’s chats and credentials are not copied.'},
  {title:'Keep working after logout',intro:'Ask your server administrator to enable lingering for your service user.',body:'Replace YOUR_USER with the regular SSH account. Lingering keeps its service manager alive after logout and starts it at boot. This is an administrator-reviewed host setting.',command:'loginctl enable-linger YOUR_USER\nloginctl show-user YOUR_USER --property=Linger\n./runtime/node hosting/check-host.mjs',note:'The host check is read-only. “Ready” checks service settings; it does not guarantee that accounts or providers are working.'},
  {title:'Connect privately from your computer',intro:'Run this tunnel on your own computer, replacing YOUR_USER and YOUR_SERVER.',body:'Keep the tunnel open, then visit http://127.0.0.1:4318. Connect your model account there and create your first bot. Stop a local Folklet first if it uses the same port.',command:'ssh -N -o ExitOnForwardFailure=yes -L 127.0.0.1:4318:127.0.0.1:4318 YOUR_USER@YOUR_SERVER',note:'Keep ports 4318 and 4320 private. Do not expose them through a public proxy or Tailscale Funnel. Your remote workspace works on the server, not on your laptop.'},
  {title:'Take your team with you',intro:'Connect the server and your phone to the same private Tailscale network.',body:'In the server’s owner interface, choose Connect iPhone. Follow setup, open the private HTTPS address in Safari, pair, then choose Share → Add to Home Screen. On your phone, open Settings → Host status to check the server.',note:'Before relying on unattended work, run a small task, restart the service, and check your account and phone again. Temporary API keys disappear on restart. Browser setup and optional account sign-in are in the full guide.'}
];
export const formatCapacity=bytes=>Number.isFinite(bytes)?(bytes/1024**3).toFixed(1)+' GB':'Unavailable';
export function formatUptime(seconds){const mins=Math.floor(seconds/60);return mins<1?'Just started':mins<60?mins+' min':mins<1440?Math.floor(mins/60)+' hr '+mins%60+' min':Math.floor(mins/1440)+' days '+Math.floor(mins%1440/60)+' hr';}
export function hostReportHTML(report) {
  const work=report.work||{},checks=report.checks||[],attention=checks.filter(c=>c.status!=='ready').length;
  return `<div class="host-hero"><span class="host-state"><i></i> Last check · ${esc(new Date(report.checkedAt).toLocaleTimeString())}</span><h2>${report.kind==='service'?'Your background workspace':'Your computer is the host'}</h2><p>${report.kind==='service'?'Your team runs here while you are away.':'Your team runs here while Folklet and this computer stay awake.'}</p></div>
  <div class="host-metrics"><div><small>Folklet uptime</small><b>${esc(formatUptime(report.uptimeSeconds))}</b></div><div><small>Free disk space</small><b>${esc(formatCapacity(report.disk?.freeBytes))}</b></div><div><small>Active / queued</small><b>${work.running||0} / ${work.queued||0}</b></div><div><small>Enabled routines</small><b>${work.routines||0}</b></div></div>
  <div class="host-section-heading"><h3>${attention?attention+' things to review':'Host checks passed'}</h3><button class="btn quiet" data-host-refresh>Refresh checks</button></div>
  <div class="host-checks">${checks.map(c=>`<article class="host-check" data-status="${esc(c.status)}"><span aria-label="${esc(c.status)}">${c.status==='ready'?'✓':c.status==='unknown'?'?':'!'}</span><div><b>${esc(c.title)}</b><p>${esc(c.detail)}</p></div></article>`).join('')}</div>
  <p class="note">Host clock: ${esc(report.timeZone||'Unknown')}. Calendar routines use this time zone.${work.nextRun?' Next scheduled run: '+esc(new Date(work.nextRun).toLocaleString())+' (your device time).':''}</p>
  <p class="note">Checked ${esc(new Date(report.checkedAt).toLocaleTimeString())}. Provider access, sleep settings and connection quality need their own checks.</p>`;
}

export function createHostingUI({api,modal}) {
  const $=id=>document.getElementById(id);let step=0;
  function shell(body,tab){modal('Your host','Keep your team within reach.',`<nav class="host-tabs" aria-label="Hosting views"><button data-host-view="status" ${tab==='status'?'aria-current="page"':''}>Host status</button><button data-host-view="setup" ${tab==='setup'?'aria-current="page"':''}>Always-on setup</button></nav><div id="hosting-view">${body}</div>`,'hosting');}
  async function status(){shell('<p class="note" role="status">Checking this host…</p>','status');const target=$('hosting-view');
    try{const report=await api('host-status');if($('modal').open&&$('hosting-view')===target)target.innerHTML=hostReportHTML(report);}
    catch{if($('modal').open&&$('hosting-view')===target)target.innerHTML='<div class="host-hero"><h2>Host unavailable</h2><p>Keep your host and Tailscale online, then try again.</p></div><button class="btn" data-host-refresh>Retry checks</button>';}
  }
  function setup(){const item=hostingSteps[step];shell(`<div class="hosting-progress" aria-label="Setup steps">${hostingSteps.map((s,i)=>`<button data-host-step="${i}" aria-label="Step ${i+1}: ${esc(s.title)}" ${i===step?'aria-current="step"':''}>${i+1}</button>`).join('')}</div><div class="host-hero"><small>STEP ${step+1} OF ${hostingSteps.length}</small><h2>${esc(item.title)}</h2><p>${esc(item.intro)}</p></div><p class="hosting-body">${esc(item.body)}</p>${item.command?`<div class="hosting-command"><pre><code>${esc(item.command)}</code></pre><button class="btn" data-host-copy>Copy commands</button><span id="host-copy-status" role="status"></span></div>`:''}${item.links?'<div class="host-provider-links"><a class="btn" href="https://www.hetzner.com/cloud/" target="_blank" rel="noopener noreferrer">Hetzner plans ↗</a><a class="btn" href="https://www.digitalocean.com/pricing/droplets" target="_blank" rel="noopener noreferrer">DigitalOcean plans ↗</a></div>':''}<p class="note">${esc(item.note)}</p><div class="hosting-next"><button class="btn quiet" data-host-step="${step-1}" ${step===0?'disabled':''}>Back</button>${step<hostingSteps.length-1?`<button class="btn primary" data-host-step="${step+1}">Next step →</button>`:'<button class="btn primary" data-host-refresh>Check this host</button>'}</div><button class="guide-link" data-settings-guide="HOSTING.md">Open the full setup and troubleshooting guide</button>`,'setup');}
  document.addEventListener('click',async event=>{const button=event.target.closest('button'),d=button?.dataset;if(!d)return;
    if(d.hostView==='status'||d.hostRefresh!==undefined)await status();
    else if(d.hostView==='setup')setup();
    else if(d.hostStep!==undefined){const next=Number(d.hostStep);if(Number.isInteger(next)&&next>=0&&next<hostingSteps.length){step=next;setup();}}
    else if(d.hostCopy!==undefined){const target=$('host-copy-status'),text=hostingSteps[step].command;if(!target||!text)return;try{await navigator.clipboard.writeText(text);if($('host-copy-status')===target)target.textContent='Copied';}catch{if($('host-copy-status')===target)target.textContent='Select the commands above to copy them.';}}
  });
  return {open:status,setup};
}
