export function createIntegrationsUI({api,modal,getBots}){
 const $=id=>document.getElementById(id),esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const live=view=>$('modal-error')===view&&$('modal').open,busy=new WeakSet();
 function error(view,e){if(live(view))view.textContent=e.message||String(e);}
 async function change(view,work){if(!live(view)||busy.has(view))return;busy.add(view);const controls=[...$('modal-content').querySelectorAll('button,input')].map(control=>[control,control.disabled]);for(const [control]of controls)control.disabled=true;try{await work();if(live(view))await open();}catch(e){error(view,e);}finally{busy.delete(view);for(const [control,disabled]of controls)control.disabled=disabled;}}
 async function open(){
  if(window.CREW_MOBILE){modal('Integrations','Read external information.','<p class="note">Manage repository access and tokens from your host computer.</p>','integrations');return;}
  modal('Integrations','Choose what each bot can read.','<div id="integration-list">Loading integrations…</div>','integrations');const view=$('modal-error'),target=$('integration-list');
  try{const items=await api('integrations');if(!live(view))return;target.innerHTML='<p class="note">GitHub access is read-only: issues and pull requests in a repository you select. Only bots you allow can use it. Retrieved content is sent to that bot’s selected model.</p><div class="settings-options">'+items.map(item=>'<button class="settings-option" data-integration-edit="'+esc(item.id)+'"><span><b>'+esc(item.name)+'</b><small>'+esc(item.repo)+' · '+(item.enabled?'Enabled':'Paused')+' · '+item.botIds.length+' allowed bots</small></span><span>›</span></button>').join('')+'</div><button class="btn primary" data-integration-new>Add GitHub repository</button><p class="note">FOLKLET cannot post, edit, merge, or execute repository code through this integration.</p>';}
  catch(e){if(live(view))target.innerHTML='<button class="btn" data-crew-integrations>Try again</button>';error(view,e);}
 }
 async function edit(id){
  if(window.CREW_MOBILE)return;modal('GitHub repository','Read-only access for selected bots.','<div id="integration-editor">Loading…</div>','integration-editor');const view=$('modal-error'),target=$('integration-editor');
  try{
   const items=id?await api('integrations'):[];if(!live(view))return;const item=items.find(item=>item.id===id)||{};if(id&&!item.id)throw Error('This integration no longer exists.');
   target.innerHTML='<form id="integration-form"><label for="integration-name">Name</label><input id="integration-name" maxlength="100" value="'+esc(item.name||'')+'" placeholder="Project issues"><label for="integration-repo">GitHub repository</label><input id="integration-repo" maxlength="140" required placeholder="owner/repository" value="'+esc(item.repo||'')+'"><label for="integration-token">GitHub token (optional for public repositories)</label><input id="integration-token" type="password" autocomplete="off" placeholder="'+(item.hasToken?'Leave blank to keep the current token':'Fine-grained token, if needed')+'"><p class="note">For private repositories, limit the token to this repository with Issues and Pull requests read permission. FOLKLET exposes only those reads. Changing the repository clears the old token unless you enter one again.</p><label class="check"><input id="integration-persist" type="checkbox" '+(item.tokenStorage==='disk'?'checked':'')+'>Remember token on this computer</label><p class="note">Otherwise it lasts only until FOLKLET quits. Remembered tokens are plaintext in FOLKLET’s private data folder, with owner-only permissions on macOS/Linux and existing folder permissions on Windows.</p><fieldset><legend>Allowed bots</legend>'+getBots().map(bot=>'<label class="check"><input type="checkbox" data-integration-bot value="'+esc(bot.id)+'" '+(item.botIds?.includes(bot.id)?'checked':'')+'>'+esc(bot.name)+'</label>').join('')+'</fieldset><p class="note">Selecting no bots keeps the repository unavailable to bots.</p><label class="check"><input type="checkbox" id="integration-enabled" '+(item.enabled!==false?'checked':'')+'>Enable this integration</label><div class="row"><button class="btn primary" type="submit">Save repository access</button>'+(id?'<button class="btn danger" type="button" data-integration-remove="'+esc(id)+'">Remove integration</button>':'')+'</div></form>';
   const form=$('integration-form'),key=$('integration-token');form.onsubmit=async event=>{event.preventDefault();if(!live(view)||busy.has(view))return;const body={id,name:$('integration-name').value||undefined,repo:$('integration-repo').value,token:key.value||undefined,persistToken:$('integration-persist').checked,enabled:$('integration-enabled').checked,botIds:[...form.querySelectorAll('[data-integration-bot]')].filter(input=>input.checked).map(input=>input.value)};await change(view,async()=>{await api('integration-save',body);key.value='';});};
  }catch(e){if(live(view))target.innerHTML='<button class="btn" data-crew-integrations>Back to integrations</button>';error(view,e);}
 }
 document.addEventListener('click',async event=>{const d=event.target.closest('button')?.dataset;if(!d)return;try{if(d.crewIntegrations!==undefined)await open();else if(d.integrationNew!==undefined)await edit();else if(d.integrationEdit)await edit(d.integrationEdit);else if(d.integrationRemove){const view=$('modal-error');await change(view,()=>api('integration-remove',{id:d.integrationRemove}));}}catch(e){error($('modal-error'),e);}});
 return {open,edit};
}
