export function createNotificationsUI({api,modal}){
 const $=id=>document.getElementById(id),esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const live=view=>$('modal-error')===view&&$('modal').open,busy=new WeakSet();
 function error(view,e){if(live(view))view.textContent=e.message||String(e);}
 async function change(view,work,after=open){if(!live(view)||busy.has(view))return;busy.add(view);const controls=[...$('modal-content').querySelectorAll('button,input')].map(control=>[control,control.disabled]);for(const [control]of controls)control.disabled=true;try{const result=await work();if(live(view))await after(result);}catch(e){error(view,e);}finally{busy.delete(view);for(const [control,disabled]of controls)control.disabled=disabled;}}
 async function open(){
  if(window.CREW_MOBILE){modal('Telegram notifications','Optional task updates.','<p class="note">Manage notification recipients and tokens from your host computer.</p>','telegram-notifications');return;}
  modal('Telegram notifications','Private, minimal task updates.','<div id="telegram-settings">Loading…</div>','telegram-notifications');const view=$('modal-error'),target=$('telegram-settings');
  try{const state=await api('notification-status');if(!live(view))return;const quiet=state.quietHours;
   target.innerHTML='<p class="note">'+(state.enabled?'Notifications are active for <b>'+esc(state.recipient.name)+'</b> (Telegram ID '+esc(state.recipient.id)+').':'Notifications are off.')+'</p><p class="note">Messages say only that a task completed, failed, or needs your input. They include no task prompts, results, bot names, or approval details. Review and answer inside Crew.</p>'+(state.error?'<p class="note" role="alert">'+esc(state.error)+'</p>':'')+(state.lastDelivery?'<p class="note">Last delivery: '+esc(state.lastDelivery.status)+'</p>':'')+'<form id="telegram-form"><label for="telegram-token">Telegram bot token</label><input id="telegram-token" type="password" autocomplete="off" placeholder="'+(state.hasToken?'Leave blank to keep the current token':'Token from BotFather')+'"><p class="note">Create a dedicated bot using Telegram’s <a href="https://t.me/BotFather" target="_blank" rel="noopener noreferrer">BotFather</a>. Pairing reads that bot’s incoming messages; use a bot with no other service or webhook attached.</p><label class="check"><input type="checkbox" id="telegram-persist" '+(state.tokenStorage==='disk'?'checked':'')+'>Remember token on this computer</label><p class="note">Unchecked tokens last until Crew quits. Remembered tokens are plaintext in Crew’s private data folder, with owner-only permissions on macOS/Linux and existing folder permissions on Windows. Changing tokens requires pairing again.</p><label for="telegram-url">Private Crew address (optional)</label><input id="telegram-url" type="url" value="'+esc(state.baseUrl)+'" placeholder="https://your-computer.example.ts.net:8443"><p class="note">Include a link back to Crew. The recipient still needs private network access and Crew phone pairing. Leave blank to send no link.</p><label class="check"><input type="checkbox" id="telegram-quiet" '+(quiet.enabled?'checked':'')+'>Use quiet hours</label><div class="row"><label>Start<input id="telegram-start" type="time" value="'+esc(quiet.start)+'"></label><label>End<input id="telegram-end" type="time" value="'+esc(quiet.end)+'"></label></div><label for="telegram-zone">Time zone</label><input id="telegram-zone" value="'+esc(quiet.timeZone)+'" placeholder="America/Vancouver"><p class="note">Updates during quiet hours are skipped, including approval reminders. Your in-app notifications remain available.</p><button class="btn primary" type="submit">Save notification settings</button></form><div class="row">'+(state.hasToken?'<button class="btn" data-telegram-pair>Create pairing code</button>':'')+(state.recipient||state.pairing?'<button class="btn danger" data-telegram-revoke>Revoke recipient</button>':'')+'</div>'+(state.pairing?'<button class="btn" data-telegram-check>Check pending pairing</button>':'')+'<p class="note">Saving settings does not send a message. After pairing, you must review the recipient and activate notifications.</p>';
   const key=$('telegram-token');$('telegram-form').onsubmit=async event=>{event.preventDefault();if(!live(view)||busy.has(view))return;const body={token:key.value||undefined,persistToken:$('telegram-persist').checked,baseUrl:$('telegram-url').value,quietHours:{enabled:$('telegram-quiet').checked,start:$('telegram-start').value,end:$('telegram-end').value,timeZone:$('telegram-zone').value}};await change(view,async()=>{await api('notification-configure',body);key.value='';});};
  }catch(e){if(live(view))target.innerHTML='<button class="btn" data-crew-notifications>Try again</button>';error(view,e);}
 }
 function pairing(value){modal('Pair Telegram','Send this code in a private chat.','<p class="note">Open your dedicated bot and send the message below. Crew will check for that exact code, then show you the recipient before enabling anything.</p><p class="phone-code">'+esc(value.message)+'</p><a class="btn primary" href="'+esc(value.url)+'" target="_blank" rel="noopener noreferrer">Open Telegram ↗</a><p class="note">Tap Start in Telegram if prompted. This code expires in five minutes.</p><button class="btn" data-telegram-check>Check for my message</button><button class="btn quiet" data-telegram-revoke>Cancel and turn off notifications</button>','telegram-pairing');}
 function preview(value){if(!value.preview){const view=$('modal-error');if(live(view))view.textContent='No matching private message yet. Send the pairing code, then check again.';return;}const p=value.preview;modal('Review notification recipient','Activate only if this is your private chat.','<div class="account-connected"><div><b>'+esc(p.name)+'</b><small>'+esc(p.username?'@'+p.username:'No username')+'</small><small>Telegram user ID: '+esc(p.id)+'</small></div></div><p class="note">Activating authorizes generic task-completion, failure, and approval reminders to this chat. No messages are sent during this setup step.</p><button class="btn primary" data-telegram-activate="'+esc(value.pairingId)+'" data-telegram-recipient="'+esc(p.id)+'">Activate notifications for this recipient</button><button class="btn quiet" data-telegram-revoke>Cancel and turn off notifications</button>','telegram-recipient');}
 document.addEventListener('click',async event=>{const d=event.target.closest('button')?.dataset;if(!d)return;const view=$('modal-error');try{if(d.crewNotifications!==undefined)await open();else if(d.telegramPair!==undefined)await change(view,()=>api('notification-pair',{}),pairing);else if(d.telegramCheck!==undefined)await change(view,()=>api('notification-check',{}),preview);else if(d.telegramActivate)await change(view,()=>api('notification-activate',{pairingId:d.telegramActivate,recipientId:d.telegramRecipient}));else if(d.telegramRevoke!==undefined)await change(view,()=>api('notification-revoke',{}));}catch(e){error(view,e);}});
 return {open};
}
