import {escapeReview as esc,reviewUI} from './review-ui-common.mjs';

export function createPluginsUI({api,modal,getBots}){
 const {$,show,live,fail,action}=reviewUI({modal});let currentReview=null;
 const pretty=value=>esc(JSON.stringify(value,null,2));
 const box=value=>'<pre class="plugin-code">'+esc(value)+'</pre>';
 const readObject=(id,label)=>{const text=$(id).value.trim();if(!text)return undefined;let value;try{value=JSON.parse(text);}catch{throw Error(label+' must be a JSON object.');}if(!value||typeof value!=='object'||Array.isArray(value))throw Error(label+' must be a JSON object.');return value;};
 const kindOf=item=>item.type==='openclaw'?'openclaw':item.transport==='stdio'?'local':'remote';
 const requirements=items=>items?.length?'<p class="note">Requirements to review</p><ul>'+items.map(item=>'<li>'+esc(item)+'</li>').join('')+'</ul>':'';
 const skillCards=items=>items?.length?items.map(item=>'<div class="learning-card"><b>'+esc(item.name)+'</b><p>'+esc(item.description)+'</p><p class="note">'+esc(item.path)+'</p>'+requirements(item.requirements)+'</div>').join(''):'<p class="note">No portable skills in this package.</p>';
 const connectionCards=items=>items?.length?items.map(item=>'<div class="learning-card"><b>'+esc(item.name)+'</b><p class="note">'+esc(subtitle(item))+' · Starts disabled</p>'+box(item.transport==='stdio'?item.command+' '+(item.args||[]).map(arg=>JSON.stringify(arg)).join(' '):item.url)+(item.cwd?'<p class="note">Working folder: '+esc(item.cwd)+'</p>':'')+requirements(item.requirements)+'</div>').join(''):'<p class="note">No portable tool connections in this package.</p>';
 const subtitle=item=>item.type==='openclaw'?'OpenClaw gateway':item.transport==='stdio'?'Local MCP server':'MCP connection';
 async function open(){
  if(window.CREW_MOBILE){show('Plugins','Connect your tools.','<p class="note">Import plugins and manage tool access on the computer running Folklet. You can answer your bots’ tool-approval requests here.</p>','plugins');return;}
  const view=show('Plugins','Bring useful tools and skills to your team.','<div id="plugin-library">Loading plugins…</div>','plugins');
  try{const [connections,packages]=await Promise.all([api('plugins'),api('plugin-packages')]);if(!live(view))return;
   $('plugin-library').innerHTML='<div class="row"><button class="btn primary" data-plugin-import>Import plugin ZIP</button><button class="btn" data-plugin-add>Add tool connection</button></div><p class="note">Import portable Hermes/OpenClaw bundles, or connect MCP tools and an OpenClaw gateway. You choose the tools and bots. Each tool call asks for approval.</p>'+
    '<h3 class="settings-label">Tool connections</h3>'+(connections.length?'<div class="settings-options">'+connections.map(item=>'<button class="settings-option" data-plugin-edit="'+esc(item.id)+'"><span><b>'+esc(item.name)+'</b><small>'+esc(subtitle(item))+' · '+(item.connected?(item.type==='openclaw'?'Configured; checked on first call':'Connected'):'Needs connection')+' · '+item.allowedTools.length+' tools selected</small></span><span>›</span></button>').join('')+'</div>':'<p class="empty-box">Connect an MCP server or import a bundle that includes one.</p>')+
    '<h3 class="settings-label">Imported packages</h3>'+(packages.length?packages.map(item=>'<div class="learning-card"><b>'+esc(item.name)+'</b><p class="note">'+esc(item.format)+' · '+(item.skillIds?.length||0)+' skills · '+(item.connectionIds?.length||0)+' connections</p><p class="note">Imported skills still need review and per-bot enabling in Skills. Connections start disabled.</p>'+(item.unsupported?.length?'<p class="note">'+esc(item.unsupported.join(' '))+'</p>':'')+'<div class="row"><button class="btn" data-crew-settings="skills">Review skills</button><button class="btn" data-plugin-package-review="'+esc(item.id)+'">Review package files</button><button class="btn danger" data-plugin-package-remove="'+esc(item.id)+'">Remove package</button></div></div>').join(''):'<p class="note">No packages imported yet.</p>')+
    '<details class="learning-card"><summary>What is compatible?</summary><p>Portable bundles can supply SKILL.md instructions and MCP tool connections. OpenClaw native tools can run through a separately installed OpenClaw gateway.</p><p>Hermes Python plugins, host-specific interfaces, hooks, channels and provider extensions need their original runtime or a dedicated adapter. The import review lists unsupported components.</p><button class="btn" data-settings-guide="PLUGINS.md">Plugin setup guide</button></details>';
  }catch(error){if(live(view)){$('plugin-library').innerHTML='<button class="btn" data-plugins-home>Try again</button>';fail(view,error);}}
 }
 function choose(){
  show('Add tool connection','Choose how the tool runs.','<div class="settings-options"><button class="settings-option" data-plugin-new="remote"><span><b>MCP server URL</b><small>Connect tools over HTTPS or a local endpoint.</small></span><span>›</span></button><button class="settings-option" data-plugin-new="local"><span><b>Local MCP program</b><small>Run a trusted server on this computer.</small></span><span>›</span></button><button class="settings-option" data-plugin-new="openclaw"><span><b>OpenClaw gateway</b><small>Use selected native plugin tools through your OpenClaw installation.</small></span><span>›</span></button></div>','plugin-add');
 }
 async function edit(id,kind='remote'){
  const view=show('Plugin connection','Review access before connecting.','<div id="plugin-editor">Loading connection…</div>','plugin-edit');
  try{const list=id?await api('plugins'):[],item=id?list.find(item=>item.id===id):{name:'',type:kind==='openclaw'?'openclaw':'mcp',transport:kind==='local'?'stdio':'streamable-http',botIds:[],allowedTools:[],tools:[]};if(!live(view))return;if(!item)throw Error('This connection was removed.');kind=kindOf(item);
   const local=kind==='local',claw=kind==='openclaw',bots=getBots();
   $('plugin-editor').innerHTML=(id?'<p class="note">'+(item.connected?(claw?'Configured. The endpoint will be checked on its first approved call.':'Connected. Choose tools and bots below, then save and reconnect to apply changes.'):'Disconnected. Review your selections and reconnect to use these tools.')+'</p>':'')+'<form id="plugin-form"><label for="plugin-name">Name</label><input id="plugin-name" required maxlength="100" value="'+esc(item.name)+'">'+
    (local?'<label for="plugin-command">Program</label><input id="plugin-command" required value="'+esc(item.command||'')+'" placeholder="node"><label for="plugin-args">Arguments, as a JSON list</label><textarea id="plugin-args" rows="3">'+pretty(item.args||[])+'</textarea><label for="plugin-cwd">Working folder (optional)</label><input id="plugin-cwd" value="'+esc(item.cwd||'')+'">':'<label for="plugin-url">'+(claw?'OpenClaw gateway URL':'MCP endpoint URL')+'</label><input id="plugin-url" type="url" required value="'+esc(item.url||'')+'" placeholder="'+(claw?'http://127.0.0.1:18789':'https://example.com/mcp')+'">')+
    '<details class="learning-card"><summary>Credentials and advanced settings</summary><p class="note">'+(item.hasSecrets?'Saved credentials are hidden. Leave fields blank to keep them for the same endpoint or program. ':'')+'Credentials stay in this session unless you explicitly remember them.</p>'+(!local?'<label for="plugin-token">Bearer token (optional)</label><input id="plugin-token" type="password" autocomplete="off"><label for="plugin-headers">Additional headers, as a JSON object</label><textarea id="plugin-headers" rows="3" placeholder="{}"></textarea>':'<label for="plugin-env">Server environment, as a JSON object</label><textarea id="plugin-env" rows="3" placeholder="{}"></textarea>')+'<label class="check"><input id="plugin-persist" type="checkbox" '+(['disk','vault','locked'].includes(item.secretStorage)?'checked':'')+'>Remember credentials in this host’s private data folder</label><p class="note">Configure and unlock Credential protection before remembering credentials. Protected values are encrypted; removing the connection clears its stored copy.</p></details>'+
    (claw?'<label for="plugin-tools">OpenClaw tool definitions</label><textarea id="plugin-tools" rows="7" required>'+pretty(item.tools||[])+'</textarea><p class="note">Paste the name, description and inputSchema for each tool you want. Folklet does not enumerate the gateway or make a test tool call. Your gateway token has broad operator access; only selected tools are exposed to bots.</p>':'')+
    '<h3 class="settings-label">Allowed tools</h3><p class="note">'+(item.tools.length?'Select individual tools. New tools remain unselected.':'Connect once to discover MCP tools, then select tools and reconnect. For OpenClaw, save your definitions first.')+'</p><div id="plugin-tool-choices">'+item.tools.map(tool=>'<label class="check"><input type="checkbox" data-plugin-tool value="'+esc(tool.name)+'" '+(item.allowedTools.includes(tool.name)?'checked':'')+'><span><b>'+esc(tool.name)+'</b><small>'+esc(tool.description||'')+'</small></span></label>').join('')+'</div>'+
    '<h3 class="settings-label">Available to these bots</h3>'+bots.map(bot=>'<label class="check"><input type="checkbox" data-plugin-bot value="'+esc(bot.id)+'" '+(item.botIds.includes(bot.id)?'checked':'')+'>'+esc(bot.name)+'</label>').join('')+
    '<div class="learning-card"><p>'+(local?'Starting this server runs its program with your normal computer-account access. It may access files and the network. Review and trust the program and arguments before connecting.':claw?'Plugin calls run in your OpenClaw gateway with that gateway’s permissions. A connection does not prove the tool works; its first approved call checks the endpoint.':'The server receives the tool arguments you approve. Review the endpoint and credentials before connecting.')+'</p>'+(local?'<label class="check"><input id="plugin-install-consent" type="checkbox">Allow this command to download and run packages (needed for npx, uvx and similar runners)</label>':'')+'<label class="check"><input id="plugin-trust" type="checkbox">I trust this connection and approve starting it</label></div>'+
    '<div class="row"><button class="btn primary" type="submit">Save and connect</button><button class="btn" type="button" data-plugin-save-only>Save disabled</button>'+(id?'<button class="btn danger" type="button" data-plugin-remove="'+esc(id)+'">Remove connection</button>':'')+'<button class="btn" type="button" data-plugins-home>Back</button></div></form>';
   const form=$('plugin-form');
   const save=async connect=>{if(!live(view))return;try{
    if(connect&&!$('plugin-trust').checked)throw Error('Review the connection and check the trust box before starting it.');
    const input={id:item.id,name:$('plugin-name').value,type:item.type,transport:item.transport,botIds:[...form.querySelectorAll('[data-plugin-bot]')].filter(n=>n.checked).map(n=>n.value),allowedTools:[...form.querySelectorAll('[data-plugin-tool]')].filter(n=>n.checked).map(n=>n.value),persistSecrets:$('plugin-persist').checked};
    if(local){input.command=$('plugin-command').value;input.cwd=$('plugin-cwd').value||undefined;input.allowPackageInstall=$('plugin-install-consent').checked;try{input.args=JSON.parse($('plugin-args').value);}catch{throw Error('Arguments must be a JSON list of strings.');}input.env=readObject('plugin-env','Environment');}
    else{input.url=$('plugin-url').value;input.token=$('plugin-token').value||undefined;input.headers=readObject('plugin-headers','Headers');}
    if(claw){try{input.tools=JSON.parse($('plugin-tools').value);}catch{throw Error('Tool definitions must be a JSON list.');}}
    await action(view,form,async()=>{const saved=await api('plugin-save',input);if(connect)await api('plugin-connect',{id:saved.id,confirmed:true});return saved;},saved=>edit(saved.id));
   }catch(error){fail(view,error);}};
   form.onsubmit=event=>{event.preventDefault();return save(true);};form.querySelectorAll('[data-plugin-save-only]')[0].onclick=()=>save(false);
  }catch(error){if(live(view)){$('plugin-editor').innerHTML='<button class="btn" data-plugins-home>Back to plugins</button>';fail(view,error);}}
 }
 function importForm(){
  const view=show('Import a plugin','Inspect the contents before adding anything.','<form id="plugin-import-form"><label for="plugin-zip">Plugin ZIP file</label><input id="plugin-zip" type="file" accept=".zip,application/zip" required><p class="note">Choose a portable Hermes/OpenClaw bundle. Importing does not run programs, install dependencies, activate skills or connect servers.</p><button class="btn primary">Inspect package</button><button class="btn" type="button" data-plugins-home>Back</button></form>','plugin-import');
  const form=$('plugin-import-form');form.onsubmit=async event=>{event.preventDefault();const file=$('plugin-zip').files?.[0];if(!file)return;await action(view,form,async()=>{if(file.size>8*1024*1024)throw Error('Choose a plugin ZIP under 8 MB.');const bytes=new Uint8Array(await file.arrayBuffer());let binary='';for(let n=0;n<bytes.length;n+=32768)binary+=String.fromCharCode(...bytes.subarray(n,n+32768));return api('plugin-inspect',{archive:btoa(binary)});},review=>reviewPackage(review));};
 }
 function reviewPackage(review){
  currentReview=review;const installed=!!review.status;
  const supported=(review.skills?.length||0)+(review.connections?.length||0),view=show('Review '+review.name,installed?'Read the original package and its compatibility notes.':'Only the supported parts below will be imported.','<div id="plugin-review"><p class="note">'+esc(review.format)+' · '+review.files.length+' files</p>'+(review.unsupported?.length?'<div class="learning-card"><b>Compatibility notes</b><ul>'+review.unsupported.map(note=>'<li>'+esc(note)+'</li>').join('')+'</ul></div>':'')+'<h3 class="settings-label">Skills</h3>'+skillCards(review.skills)+'<h3 class="settings-label">Tool connections</h3>'+connectionCards(review.connections)+'<details open><summary>Included files — choose one to read</summary><div class="settings-options">'+review.files.map(file=>'<button class="settings-option" data-plugin-file="'+esc(file)+'"><span>'+esc(file)+'</span><span>›</span></button>').join('')+'</div></details><p class="note">Skills become pending drafts. Connections stay disabled with no bot access. Supporting files are kept privately and can contain credentials from the original package. Imported connections do not activate those credentials. Dependency installers and native plugin entry points are not run.</p><div class="row"><button class="btn primary" id="plugin-install" '+(supported&&!installed?'':'disabled')+'>'+(installed?'Already imported':'Import supported parts')+'</button><button class="btn" data-plugin-import>Choose another ZIP</button><button class="btn" data-plugins-home>Back</button></div>'+(supported?'':'<p class="note">No portable skills or MCP connections were found. This package needs its original host runtime.</p>')+'</div>','plugin-review');
  $('plugin-install').onclick=()=>installed?undefined:action(view,$('plugin-review'),()=>api('plugin-install',{id:review.id,reviewHash:review.reviewHash,confirmed:true}),open);
 }
 async function filePreview(file){
  const review=currentReview;if(!review)return;
  const view=show('Read package file',file,'<div id="plugin-file-content">Loading file…</div><button class="btn" data-plugin-review-back>Back to package review</button>','plugin-file');
  try{const result=await api('plugin-file',{id:review.id,path:file,reviewHash:review.reviewHash});if(!live(view))return;$('plugin-file-content').innerHTML='<p class="note">'+result.bytes+' bytes'+(result.truncated?' · Preview truncated; the full original is retained.':'')+'</p>'+(result.binary?'<p class="note">Binary file; no text preview is available.</p>':box(result.text));}catch(error){if(live(view)){$('plugin-file-content').innerHTML='<p class="note">This file could not be verified. Inspect the package again before importing.</p>';fail(view,error);}}
 }
 async function installedReview(id){const view=show('Package files','Read the imported source.','<p>Loading package…</p>','plugin-loading');try{const packages=await api('plugin-packages');if(!live(view))return;const item=packages.find(p=>p.id===id);if(!item)throw Error('This package was removed.');reviewPackage(item);}catch(error){fail(view,error);}}
 function remove(id,packageOnly=false){
  const view=show(packageOnly?'Remove package?':'Remove connection?',packageOnly?'Remove its tool connections and owned package files.':'Stop its tools and remove saved credentials.','<div id="plugin-remove-confirm"><p class="note">'+(packageOnly?'Imported skills will be disabled. Existing conversations remain in your workspace.':'Bots will lose access to this connection. Pending tool requests will be cancelled.')+'</p><button class="btn danger" id="plugin-confirm-remove">Remove</button> <button class="btn" data-plugins-home>Cancel</button></div>','plugin-remove');
  $('plugin-confirm-remove').onclick=()=>action(view,$('plugin-remove-confirm'),()=>api(packageOnly?'plugin-package-remove':'plugin-remove',{id}),open);
 }
 document.addEventListener('click',async event=>{const d=event.target.closest('button')?.dataset;if(!d)return;try{if(d.pluginsHome!==undefined)await open();else if(d.pluginAdd!==undefined)choose();else if(d.pluginNew)await edit(null,d.pluginNew);else if(d.pluginEdit)await edit(d.pluginEdit);else if(d.pluginImport!==undefined)importForm();else if(d.pluginRemove)remove(d.pluginRemove);else if(d.pluginPackageRemove)remove(d.pluginPackageRemove,true);else if(d.pluginPackageReview)await installedReview(d.pluginPackageReview);else if(d.pluginFile)await filePreview(d.pluginFile);else if(d.pluginReviewBack!==undefined&&currentReview)reviewPackage(currentReview);}catch(error){fail($('modal-error'),error);}});
 return {open,edit,importForm,reviewPackage};
}
