const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function createRecallUI({api,modal,getBots,onSource}){
 let selected;
 async function open(botId){
  selected=botId||selected||getBots()[0]?.id;modal('Past work','Choose what each bot can recall.','<div id="recall-view">Loading…</div>','recall');const target=document.getElementById('recall-view'),error=document.getElementById('modal-error');
  try{if(!selected){target.innerHTML='<div class="empty-box">Create a bot to start recalling its work.</div>';return;}const settings=await api('recall-settings?botId='+encodeURIComponent(selected));if(!target.isConnected)return;
   target.innerHTML='<div class="model-provider-list">'+getBots().map(b=>'<button class="btn '+(b.id===selected?'primary':'')+'" data-recall-bot="'+esc(b.id)+'">'+esc(b.name)+'</button>').join('')+'</div><p class="note">This bot can search its own private conversations. Shared chats are included only when you enable them below. Search and saved history stay on your FOLKLET host; retrieved excerpts go to the model working on the task.</p><label class="check"><input id="recall-shared" type="checkbox" '+(settings.includeShared?'checked':'')+'> Allow recall from shared channels this bot belongs to</label><form id="recall-search" class="stack"><label>Try a search<input id="recall-query" maxlength="300" placeholder="A project, decision, or phrase" required></label><button class="btn primary">Search past work</button></form><div id="recall-results"></div>';
   target.querySelectorAll('[data-recall-bot]').forEach(button=>button.onclick=()=>open(button.dataset.recallBot));
   target.querySelector('#recall-shared').onchange=async event=>{const input=event.target;input.disabled=true;try{await api('recall-settings-save',{botId:selected,includeShared:input.checked});error.textContent='';}catch(e){input.checked=!input.checked;error.textContent=e.message;}finally{input.disabled=false;}};
   target.querySelector('#recall-search').onsubmit=async event=>{event.preventDefault();const submit=event.submitter;submit.disabled=true;try{const results=await api('recall-search',{botId:selected,query:target.querySelector('#recall-query').value});if(!target.isConnected)return;target.querySelector('#recall-results').innerHTML=results.length?results.map((r,i)=>'<article class="learning-card"><small>'+esc(r.botName)+' · '+esc(new Date(r.at).toLocaleString())+'</small><p>'+esc(r.snippet)+'</p><button class="btn" data-recall-source="'+i+'">Open conversation</button></article>').join(''):'<div class="empty-box">No matching conversations in this bot’s permitted history.</div>';target.querySelectorAll('[data-recall-source]').forEach(button=>button.onclick=()=>onSource?.(results[Number(button.dataset.recallSource)].url));error.textContent='';}catch(e){error.textContent=e.message;}finally{submit.disabled=false;}};
  }catch(e){if(target.isConnected){target.innerHTML='<button class="btn" id="recall-retry">Retry loading</button>';target.querySelector('button').onclick=()=>open(selected);error.textContent=e.message;}}
 }
 return {open};
}
