export function createReliabilityUI({api,modal,draftStorage,onDraftChange=()=>{}}){
 const $=id=>document.getElementById(id),esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 let page='home',pushState=null,usageState=null,pendingRestore=null;
 const field=(id,label,type='text',value='',extra='')=>'<label for="'+id+'">'+esc(label)+'</label><input id="'+id+'" type="'+type+'" value="'+esc(value)+'" '+extra+'>';
 const button=(name,label,primary=false)=>'<button type="button" class="btn '+(primary?'primary':'')+'" data-reliability="'+name+'">'+esc(label)+'</button>';
 const row=(name,title,detail)=>'<button class="settings-option" data-reliability="'+name+'"><span><b>'+esc(title)+'</b><small>'+esc(detail)+'</small></span><span>›</span></button>';
 function error(e){if($('modal-error'))$('modal-error').textContent=e.message;}
 function show(title,description,body){modal(title,description,'<div id="reliability-view">'+body+'<p id="reliability-status" class="note" role="status"></p></div>'+(page==='home'?'':'<div class="reliability-back">'+button('home','Back to Data & reliability')+'</div>'),'reliability-'+page);return $('reliability-view');}
 async function load(title,description,work,render){const target=show(title,description,'Loading…');try{const value=await work();if($('reliability-view')===target)target.innerHTML=render(value);}catch(e){if($('reliability-view')===target){target.innerHTML=button(page,'Try again');error(e);}}}
 async function open(next='home'){page=next;pendingRestore=null;
  if(next==='home'){show('Data & reliability','Keep your team useful wherever you work.','<div class="settings-options">'+row('drafts','Draft autosave','Optional drafts saved on this device for seven days.')+row('push','Phone notifications','Generic completion and approval alerts.')+row('usage','Usage & limits','API request counts and estimated spending.')+(window.CREW_MOBILE?'':row('backups','Backups & migration','Encrypted snapshots and a separate restore workspace.')+row('vault','Credential protection','Protect remembered keys and unlock your vault.')+row('catalog','Starter catalog','Pinned MCP setup and portable skill starters.')+row('updates','App updates','Check official releases and update with a backup.'))+'</div>');return;}
  if(next==='drafts'){show('Draft autosave','This setting applies only to this device.','<p class="note">Opt in to save unsent text and attachment references in this browser. Anyone using this browser profile may read them. Drafts expire after seven days; files must still exist on the host. Drafts are never automatically sent.</p><label class="check"><input id="draft-enabled" type="checkbox" '+(draftStorage?.enabled()?'checked':'')+'>Save drafts on this device</label>'+button('draft-save','Save preference',true)+button('draft-clear','Clear saved drafts')+'<p class="note">Up to 30 drafts and 512 KB. Browser storage can be cleared by the OS. '+esc(draftStorage?.error)+'</p>');return;}
  if(next==='vault'){if(window.CREW_MOBILE)return open();await load('Credential protection','Remembered keys can be encrypted; session-only connections remain available.',()=>api('vault-status'),value=>'<p class="note">'+esc(value.configured?(value.unlocked?'Vault unlocked for this host session.':'Vault locked. Unlock to use protected connections.'):'Choose how to protect remembered API, plugin and notification credentials. Existing saved credentials are migrated when you configure protection.')+'</p>'+(!value.configured?'<label for="vault-mode">Protection method</label><select id="vault-mode"><option value="password">Password vault — portable and server friendly</option><option value="os">OS protection — this computer account</option></select>':'')+field('vault-password',value.mode==='os'?'Password not needed for OS protection':'Vault password','password','','autocomplete="new-password"')+(!value.configured?field('vault-confirm','Confirm password when using a password vault','password'):'')+button(value.configured?'vault-unlock':'vault-configure',value.configured?'Unlock':'Configure and encrypt remembered credentials',true)+'<p class="note">Windows uses current-user DPAPI, Mac uses Keychain, and Linux desktop requires Secret Service (secret-tool). A password vault needs unlocking after a restart; the server guide covers systemd credentials. Old copies and backups are not erased.</p>');return;}
  if(next==='backups'){if(window.CREW_MOBILE)return open();await load('Backups & migration','Save an encrypted copy, then verify recovery in a separate workspace.',()=>api('backup-status'),value=>'<p class="note">Includes chats, bot files, skills, settings and protected credentials. Browser sign-ins and phone pairings are excluded. Limit: 64 MB / 10,000 files. Finish queued and active work first. Download a copy to another device for protection from disk failure.</p>'+field('backup-password','Backup password (12 or more characters)','password','','minlength="12" autocomplete="new-password"')+button('backup-create','Create encrypted backup',true)+'<h3 class="settings-label">Scheduled backups</h3><label class="check"><input id="backup-enabled" type="checkbox" '+(value.enabled?'checked':'')+'>Back up automatically while work is idle</label>'+field('backup-hours','Every (hours)','number',value.intervalHours,'min="1" max="168"')+field('backup-keep','Keep the newest backups','number',value.keep,'min="1" max="30"')+button('backup-schedule','Save backup schedule')+'<p class="note">A protected, unlocked vault is needed for scheduled backups. '+esc(value.lastError)+'</p><div class="settings-options">'+value.backups.map(b=>'<button class="settings-option" data-backup-download="'+esc(b.id)+'"><span><b>'+esc(new Date(b.createdAt).toLocaleString())+'</b><small>'+Math.ceil(b.bytes/1024)+' KB · Download encrypted backup</small></span><span>↓</span></button>').join('')+'</div><h3 class="settings-label">Restore or move your workspace</h3><input id="backup-upload" type="file" accept=".folklet-backup">'+field('restore-password','Password used for this backup','password')+button('backup-inspect','Inspect backup')+'<div id="backup-preview"></div>');return;}
  if(next==='usage'){
   await load('Usage & limits','API requests and provider-reported tokens. ChatGPT subscription usage is separate.',()=>api('usage-status'),value=>{
    usageState=value;
    const metrics='<div class="host-metrics"><div><small>API requests today</small><b>'+value.today.requests+'</b></div><div><small>Estimated USD</small><b>$'+value.today.estimatedUSD.toFixed(4)+'</b></div><div><small>Reported input tokens</small><b>'+value.today.inputTokens+'</b></div><div><small>Reported output tokens</small><b>'+value.today.outputTokens+'</b></div></div>';
    const alert=value.alert?'<p class="note" role="status">'+(value.alert==='budget-reached'?'Estimated budget reached. New API requests are paused.':'Estimated spending has reached 80% of your daily budget.')+'</p>':'';
    const note='<p class="note">'+value.today.unpricedRequests+' unpriced requests; '+value.today.unknownUsage+' without complete usage. Day: '+esc(value.day)+' UTC. '+esc(value.note)+'</p>';
    if(window.CREW_MOBILE)return metrics+alert+note+'<p class="note">Change limits and prices on the host.</p>';
    return metrics+alert+note+
     field('usage-requests','Daily API request limit (0 = off)','number',value.settings.dailyRequests,'min="0" max="100000"')+
     field('usage-budget','Daily estimated budget, USD (0 = off)','number',value.settings.dailyBudgetUSD,'min="0" step="0.01"')+button('usage-save','Save limits',true)+
     '<h3 class="settings-label">Model price estimates</h3><p class="note">Use current prices from your provider. Unknown models remain unpriced.</p><div id="usage-rates">'+
     value.settings.rates.map((r,i)=>'<p>'+esc(r.model)+' · $'+r.inputPerMillion+' input / $'+r.outputPerMillion+' output per million tokens <button class="btn" data-rate-remove="'+i+'">Remove</button></p>').join('')+
     '</div><label for="usage-provider">Connection</label><select id="usage-provider"></select>'+field('usage-model','Exact model ID')+
     field('usage-input','Input USD per million tokens','number','','min="0" step="0.001"')+field('usage-output','Output USD per million tokens','number','','min="0" step="0.001"')+button('usage-price','Save model price');
   });
   if(!window.CREW_MOBILE&&$('usage-provider')){
    const target=$('usage-provider');
    try{const providers=await api('providers');if($('usage-provider')===target){const choices=providers.filter(p=>p.id!=='codex');target.innerHTML=choices.length?choices.map(p=>'<option value="'+esc(p.id)+'">'+esc(p.name)+'</option>').join(''):'<option value="">Add an API connection first</option>';if(!choices.length)target.insertAdjacentHTML('afterend','<button class="btn" data-crew-settings="connections">Open Connections</button>');}}catch(e){error(e);}
   }
   return;
  }
  if(next==='push'){await load('Phone notifications','Alerts contain generic status only. Open Folklet to read or approve work.',()=>api('push-status'),value=>{pushState=value;return '<p class="note">'+(value.enabled?'Host push is enabled.':'Enable push on the host before subscribing a phone.')+(value.enabled&&!value.unlocked?' Unlock the host credential vault to deliver alerts.':'')+' '+esc(value.error)+'</p>'+(window.CREW_MOBILE?'<p class="note">On iPhone, add Folklet to the Home Screen, open that app, and allow notifications. You need the host online; open the private connection to review work.</p>'+button('push-subscribe',value.subscribed?'Refresh this phone’s subscription':'Enable notifications on this phone',true)+button('push-unsubscribe','Turn off notifications on this phone'):'<label class="check"><input id="push-enabled" type="checkbox" '+(value.enabled?'checked':'')+'>Enable phone push on this host</label>'+field('push-subject','Public HTTPS contact URL for push services','url',value.subject)+'<label class="check"><input id="push-quiet" type="checkbox" '+(value.quietHours.enabled?'checked':'')+'>Use quiet hours (no catch-up alerts)</label>'+field('push-start','Quiet hours start','time',value.quietHours.start)+field('push-end','Quiet hours end','time',value.quietHours.end)+field('push-zone','IANA time zone','text',value.quietHours.timeZone)+button('push-configure','Save push settings',true)+'<p class="note">'+value.deviceCount+' active paired-device subscriptions. Configure credential protection first. Notification delivery uses the browser’s Apple, Google or Mozilla push service.</p>');});return;}
  if(next==='catalog'){if(window.CREW_MOBILE)return open();await load('Starter catalog','Review a recipe, then choose exactly what your bot can use.',()=>api('plugin-catalog'),items=>items.map(item=>'<div class="learning-card"><b>'+esc(item.name)+' · '+esc(item.version)+'</b><p>'+esc(item.description)+'</p><p class="note">'+esc(item.requirements)+'</p><p class="note">'+esc(item.verification)+'</p><a class="btn" href="'+esc(item.source)+'" target="_blank" rel="noopener noreferrer">Publisher documentation ↗</a>'+(item.kind==='connection'?field('catalog-folder','Folder this MCP server may access')+button('catalog-filesystem','Prepare disabled connection'): '<button class="btn" data-catalog-skill="'+esc(item.id)+'">Import skill for review</button>')+'</div>').join(''));return;}
  if(next==='updates'){if(window.CREW_MOBILE)return open();show('App updates','Keep a recoverable copy before replacing your installation.','<p class="note">Checking contacts the official GitHub repository. Downloads and installation stay under your control.</p><label class="check"><input id="update-previews" type="checkbox">Include community previews</label>'+button('updates-check','Check GitHub releases',true)+'<div id="update-result"></div><ol><li>Create and download a backup.</li><li>Read the release notes and checksums.</li><li>Stop Folklet, extract the new version separately and follow its migration guide.</li></ol>');return;}
 }
 async function download(id){const r=await fetch('/api/backup-download?id='+encodeURIComponent(id),{headers:{'X-Crew-Token':window.CREW_TOKEN}});if(!r.ok)throw Error('Backup download failed.');const url=URL.createObjectURL(await r.blob()),a=document.createElement('a');a.href=url;a.download=id;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 async function base64(file){if(!file||file.size>128*1024*1024)throw Error('Choose an encrypted backup under 128 MB.');return await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]);reader.onerror=()=>reject(Error('Could not read the backup.'));reader.readAsDataURL(file);});}
 document.addEventListener('click',async event=>{const target=event.target.closest('button');if(!target)return;const d=target.dataset;if(!d.reliability&&!d.backupDownload&&!d.catalogSkill&&d.rateRemove===undefined)return;if(target.disabled)return;target.disabled=true;const owner=$('reliability-view');try{
  if(d.backupDownload){await download(d.backupDownload);return;}
  if(d.catalogSkill){await api('catalog-skill',{id:d.catalogSkill});if($('reliability-view')===owner)show('Skill imported','Review it under Skills before enabling it.','<button class="btn primary" data-crew-settings="skills">Review skills</button>');return;}
  if(d.rateRemove!==undefined){const rates=usageState.settings.rates.filter((_,i)=>i!==Number(d.rateRemove));await api('usage-configure',{...usageState.settings,rates});if($('reliability-view')===owner)await open('usage');return;}
  const action=d.reliability;
  if(['home','drafts','vault','backups','usage','push','catalog','updates'].includes(action)){await open(action);return;}
  if(action==='draft-save'){draftStorage.enable($('draft-enabled').checked);onDraftChange();if(draftStorage.error)throw Error(draftStorage.error);$('reliability-status').textContent='Draft preference saved.';}
  else if(action==='draft-clear'){draftStorage.enable(false);draftStorage.clear();await open('drafts');$('reliability-status').textContent='Saved drafts cleared. Autosave is now off; your open draft stays in this page.';}
  else if(action==='vault-configure'){const mode=$('vault-mode').value,password=$('vault-password').value;if(mode==='password'&&password!==$('vault-confirm').value)throw Error('The passwords do not match.');await api('vault-configure',{mode,password});if($('reliability-view')===owner)await open('vault');}
  else if(action==='vault-unlock'){await api('vault-unlock',{password:$('vault-password').value});if($('reliability-view')===owner)await open('vault');}
  else if(action==='backup-create'){await api('backup-create',{password:$('backup-password').value});if($('reliability-view')===owner)await open('backups');}
  else if(action==='backup-schedule'){await api('backup-configure',{enabled:$('backup-enabled').checked,intervalHours:Number($('backup-hours').value),keep:Number($('backup-keep').value),password:$('backup-password').value||undefined});if($('reliability-view')===owner)await open('backups');}
  else if(action==='backup-inspect'){const file=$('backup-upload').files[0],password=$('restore-password').value;const input={base64:await base64(file),password};if($('reliability-view')!==owner)return;const value=await api('backup-inspect',input);if($('reliability-view')===owner){pendingRestore=input;$('backup-preview').innerHTML='<p>'+value.files+' files · '+Math.ceil(value.bytes/1024)+' KB · '+esc(new Date(value.createdAt).toLocaleString())+'</p><p class="note">Restores into a separate folder. Routines are paused, active tasks interrupted, and tool connections disabled. The current workspace stays open.</p>'+button('backup-restore','Restore a separate workspace',true);}}
  else if(action==='backup-restore'){if(!pendingRestore)throw Error('Inspect a backup first.');const result=await api('backup-restore',pendingRestore);pendingRestore=null;if($('reliability-view')===owner)show('Workspace restored','Your current workspace has not been replaced.','<p>Restored folder:</p><pre class="plugin-code">'+esc(result.destination)+'</pre><p class="note">Stop Folklet before opening this copy. Use this folder as CREW_DATA when launching. Unlock its vault with the backup password, reconnect accounts, and review paused routines.</p><button class="btn" data-settings-guide="RECOVERY.md">Open recovery instructions</button>');}
  else if(action==='usage-save'){await api('usage-configure',{...usageState.settings,dailyRequests:Number($('usage-requests').value),dailyBudgetUSD:Number($('usage-budget').value)});if($('reliability-view')===owner)await open('usage');}
  else if(action==='usage-price'){if(!$('usage-provider').value||!$('usage-input').value.trim()||!$('usage-output').value.trim())throw Error('Choose a connection and enter both prices. Enter 0 only if your provider lists that price as free.');const rate={providerId:$('usage-provider').value,model:$('usage-model').value.trim(),inputPerMillion:Number($('usage-input').value),outputPerMillion:Number($('usage-output').value)};await api('usage-configure',{...usageState.settings,rates:usageState.settings.rates.filter(r=>r.providerId!==rate.providerId||r.model!==rate.model).concat(rate)});if($('reliability-view')===owner)await open('usage');}
  else if(action==='push-configure'){await api('push-configure',{enabled:$('push-enabled').checked,subject:$('push-subject').value,quietHours:{enabled:$('push-quiet').checked,start:$('push-start').value,end:$('push-end').value,timeZone:$('push-zone').value}});if($('reliability-view')===owner)await open('push');}
  else if(action==='push-subscribe'){const pushOptions=pushState;if(!pushOptions?.enabled||!pushOptions.unlocked)throw Error('Enable push and unlock credential protection on the host first.');if(!('serviceWorker' in navigator)||!('PushManager' in window)||!('Notification' in window))throw Error('Open the installed Home Screen app in a browser with Web Push support.');if(await Notification.requestPermission()!=='granted')throw Error('Notification permission was not granted. Check this app’s notification settings.');const registration=await navigator.serviceWorker.ready,key=Uint8Array.from(atob(pushOptions.publicKey.replaceAll('-','+').replaceAll('_','/')),c=>c.charCodeAt(0)),subscription=await registration.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:key});await api('push-subscribe',{subscription:subscription.toJSON()});if($('reliability-view')===owner)await open('push');}
  else if(action==='push-unsubscribe'){await api('push-unsubscribe',{});const registration=await navigator.serviceWorker.getRegistration();await (await registration?.pushManager.getSubscription())?.unsubscribe();if($('reliability-view')===owner)await open('push');}
  else if(action==='catalog-filesystem'){await api('catalog-prepare',{id:'filesystem',folder:$('catalog-folder').value});if($('reliability-view')===owner)show('Connection prepared','No package has been started or installed.','<p>Open Plugins, review the new connection, select your bots and tools, and approve starting it when ready.</p><button class="btn primary" data-crew-settings="plugins">Review connection</button>');}
  else if(action==='updates-check'){const result=await api('update-check',{includePreviews:$('update-previews').checked});if($('reliability-view')===owner)$('update-result').innerHTML=result.release?'<div class="learning-card"><b>'+esc(result.release.name)+'</b><p>'+esc(result.release.tag)+'</p><a class="btn primary" href="'+esc(result.release.url)+'" target="_blank" rel="noopener noreferrer">Review release and downloads ↗</a><p class="note">Current source version: '+esc(result.current)+'. Check whether this source contains unreleased changes before replacing it.</p></div>':'<p class="note">No matching published release was found. Try including previews.</p>';}
 }catch(e){if($('reliability-view')===owner)error(e);}finally{target.disabled=false;}});
 return {open};
}
