import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
import {CredentialVault,osKeyStore,passwordWrap} from './credential-vault.mjs';
import {Store} from './store.mjs';import {ProviderStore} from './providers.mjs';import {IntegrationStore} from './integrations.mjs';import {TelegramNotifications} from './notifications.mjs';import {PluginConnections} from './plugin-connections.mjs';
import {createBackup,inspectBackup,restoreBackup,Backups} from './backups.mjs';import {DraftStorage} from './draft-storage.mjs';import {StateSync,historyPage} from './state-sync.mjs';import {SyncClient} from './sync-client.mjs';import {Usage} from './usage.mjs';import {PushNotifications,pushSubscription} from './push-notifications.mjs';import {catalogSkill,catalogRecipe} from './plugin-catalog.mjs';import {Skills} from './skills.mjs';import {checkUpdates} from './updates.mjs';
import {publisherPlan} from './scripts/Publisher-Sign.mjs';
const password='fixture password with enough length';
function fixture(t){const root=fs.mkdtempSync(path.join(os.tmpdir(),'folklet-reliability-'));t.after(()=>{assert(path.resolve(root).startsWith(path.resolve(os.tmpdir())+path.sep));fs.rmSync(root,{recursive:true,force:true});});return root;}
function memoryStorage(){const values=new Map();return {getItem:key=>values.get(key)??null,setItem:(key,value)=>values.set(key,value),removeItem:key=>values.delete(key),values};}
test('password vault authenticates both data and field identity and never writes its key in plaintext',t=>{const root=fixture(t),vault=new CredentialVault(root);vault.configure({password});const sealed=vault.protect('fixture-secret','provider:a');assert.equal(vault.reveal(sealed,'provider:a'),'fixture-secret');assert.throws(()=>vault.reveal(sealed,'provider:b'),/password|damaged/);assert(!fs.readFileSync(vault.file,'utf8').includes(vault.key.toString('hex')));vault.close();assert.equal(vault.reveal(sealed,'provider:a'),null);assert.throws(()=>vault.unlock('wrong password value'),/password|damaged/);vault.unlock(password);assert.equal(vault.reveal(sealed,'provider:a'),'fixture-secret');});
test('protected provider credentials survive a locked restart without exposure',t=>{const root=fixture(t),vault=new CredentialVault(root);vault.configure({password});const providers=new ProviderStore(root,{vault});const provider=providers.save({type:'openai',apiKey:'fixture-api-secret',persistKey:true});assert.equal(provider.keyStorage,'vault');assert(!fs.readFileSync(providers.keyFile,'utf8').includes('fixture-api-secret'));vault.close();const nextVault=new CredentialVault(root),next=new ProviderStore(root,{vault:nextVault});assert.equal(next.list()[1].keyStorage,'locked');assert.throws(()=>next.getConnection(provider.id),/Unlock/);nextVault.unlock(password);assert.equal(next.getConnection(provider.id).key,'fixture-api-secret');});
test('legacy provider keys migrate only when vault protection is configured',t=>{const root=fixture(t),old=new ProviderStore(root);old.save({type:'openai',apiKey:'legacy-fixture',persistKey:true});const vault=new CredentialVault(root),next=new ProviderStore(root,{vault});assert.equal(next.list()[1].keyStorage,'disk');vault.configure({password});next.persist();assert(!fs.readFileSync(next.keyFile,'utf8').includes('legacy-fixture'));assert.equal(next.list()[1].keyStorage,'vault');});
test('GitHub, Telegram and plugin credentials use field-bound encrypted storage',t=>{const root=fixture(t),vault=new CredentialVault(root),store=new Store(root),bot=store.create({name:'Sample'});vault.configure({password});const integrations=new IntegrationStore({dataRoot:root,store,vault});integrations.save({repo:'example/repository',botIds:[bot.id],token:'github-fixture-secret',persistToken:true});const telegram=new TelegramNotifications({dataRoot:root,vault});telegram.configure({token:'123456:'+ 't'.repeat(24),persistToken:true});const plugins=new PluginConnections({dataRoot:root,store,vault});plugins.save({name:'Sample',type:'mcp',transport:'streamable-http',url:'https://example.com/mcp',token:'plugin-fixture-secret',persistSecrets:true});for(const file of ['integrations.json','telegram-notifications.json','plugin-connections.json'])assert.match(fs.readFileSync(path.join(root,file),'utf8'),/folklet-secret-v1/);assert(!JSON.stringify(integrations.list()).includes('github-fixture-secret'));vault.close();assert.equal(new TelegramNotifications({dataRoot:root,vault}).status().enabled,false);assert.equal(new PluginConnections({dataRoot:root,store,vault}).list()[0].secretStorage,'locked');});
test('Windows native protector round-trips with no secret in arguments',{skip:process.platform!=='win32'},()=>{const key='a'.repeat(64),wrapped=osKeyStore('put','fixture',key);assert.notEqual(wrapped,key);assert.equal(osKeyStore('get','fixture',wrapped),key);});
test('OS keychain commands send sensitive values on stdin and reject unavailable stores',()=>{let observed;osKeyStore('put','a'.repeat(32),'b'.repeat(64),{platform:'linux',run:(cmd,args,options)=>{observed={cmd,args,options};return {status:0,stdout:''};}});assert(!observed.args.join(' ').includes('b'.repeat(64)));assert.equal(observed.options.input,'b'.repeat(64));assert.throws(()=>osKeyStore('get','x','',{platform:'linux',run:()=>({status:1})}),/unavailable/);});
test('encrypted backup verifies and restores files, protected credentials and paused work separately',t=>{const root=fixture(t),source=path.join(root,'source'),store=new Store(source),bot=store.create({name:'Sample'}),vault=new CredentialVault(source);vault.configure({password});const provider=new ProviderStore(source,{vault});provider.save({type:'openai',apiKey:'backup-key-fixture',persistKey:true});fs.writeFileSync(path.join(bot.cwd,'notes.txt'),'My sample work');store.enqueue(bot.id,'Do not replay');store.routine({botId:bot.id,prompt:'Do not start',minutes:10,enabled:true});fs.writeFileSync(path.join(source,'mobile.json'),'private paired phone');const bytes=createBackup(source,password,{vault});assert(!bytes.includes(Buffer.from('My sample work')));assert(!bytes.includes(Buffer.from('backup-key-fixture')));const report=inspectBackup(bytes,password);assert(!report.payload.files.some(f=>f.path==='mobile.json'));const destination=path.join(root,'restored');restoreBackup(bytes,password,destination);const restored=new Store(destination);assert.equal(fs.readFileSync(path.join(restored.db.bots[0].cwd,'notes.txt'),'utf8'),'My sample work');assert.equal(restored.db.tasks[0].status,'interrupted');assert.equal(restored.db.routines[0].enabled,false);const newVault=new CredentialVault(destination);newVault.unlock(password);assert.equal(new ProviderStore(destination,{vault:newVault}).getConnection(provider.list()[1].id).key,'backup-key-fixture');assert.throws(()=>restoreBackup(bytes,password,destination),/new, empty/);assert.equal(store.db.tasks[0].status,'queued');});
test('wrong passwords and tampering cannot create a restore destination',t=>{const root=fixture(t),source=path.join(root,'source');new Store(source);const bytes=createBackup(source,password),destination=path.join(root,'restored');assert.throws(()=>restoreBackup(bytes,'another wrong password',destination));const damaged=JSON.parse(bytes);damaged.tag=Buffer.alloc(16).toString('base64');assert.throws(()=>restoreBackup(Buffer.from(JSON.stringify(damaged)),password,destination));assert(!fs.existsSync(destination));});
test('authenticated malicious archive paths and case collisions are rejected before restore',t=>{const root=fixture(t);for(const paths of [['../outside'],['folder/A','folder/a'],['C:/escape'],['nul.txt']]){const files=paths.map(name=>({path:name,data:'',sha256:'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855'}));const envelope={format:'folklet-backup-v1',...passwordWrap(Buffer.from(JSON.stringify({version:1,files})),password,'folklet-backup-v1')};assert.throws(()=>restoreBackup(Buffer.from(JSON.stringify(envelope)),password,path.join(root,'new')));assert(!fs.existsSync(path.join(root,'new')));}});
test('scheduled backups require an unlocked vault and never run active work',t=>{const root=fixture(t),store=new Store(root),vault=new CredentialVault(root);vault.configure({password});let idle=false;const backups=new Backups({dataRoot:root,vault,isIdle:()=>idle,now:()=>Date.now()+86400000});backups.configure({enabled:true,password,intervalHours:1,keep:2});backups.tick();assert.equal(backups.list().length,0);idle=true;backups.tick();assert.equal(backups.list().length,1);assert(!fs.readFileSync(backups.file,'utf8').includes(password));});
test('draft autosave is optional, scoped, expires, clears and keeps attachment ownership',()=>{const storage=memoryStorage();let now=1000000000;const draft=new DraftStorage({storage,now:()=>now});draft.bind('workspace-a');draft.save({bot:'unsaved'},{});assert.equal(storage.values.size,0);draft.enable(true);draft.save({bot:'remember this'},{bot:[{owner:'bot',path:'attachments/file.txt'},{owner:'bot',path:'../secret'}]});const other=new DraftStorage({storage,now:()=>now});other.bind('workspace-a');assert.equal(other.load().drafts.bot,'remember this');assert.deepEqual(other.load().attachments.bot,[{owner:'bot',path:'attachments/file.txt'}]);other.bind('workspace-b');assert.deepEqual(other.load().drafts,{});other.bind('workspace-a');now+=8*86400000;assert.deepEqual(other.load().drafts,{});other.enable(false);assert(!other.enabled());});
test('draft storage failure is visible and never pretends a draft was saved',()=>{const storage=memoryStorage(),draft=new DraftStorage({storage});draft.bind('sample');draft.enable(true);storage.setItem=()=>{throw Error('quota');};draft.save({bot:'keep in open page'},{});assert.match(draft.error,/autosave failed/);});
test('delta sync is tiny when unchanged and catches in-place task edits',()=>{const sync=new StateSync(),client=new SyncClient(),state={workspaceId:'sample',bots:[{id:'bot',messages:Array.from({length:200},(_,i)=>({id:'m'+i,at:i,text:'message '+i})),events:[]}],tasks:[{id:'t',status:'running'}]};const first=sync.update(state);assert.equal(first.state.bots[0].messages.length,60);client.apply(first);const unchanged=sync.update(state,first.cursor);assert(unchanged.unchanged);assert(JSON.stringify(unchanged).length<150);state.tasks[0].status='completed';const patch=sync.update(state,first.cursor);assert.equal(patch.bots.length,0);assert.equal(patch.changes.tasks[0].status,'completed');assert.equal(client.apply(patch).tasks[0].status,'completed');const page=historyPage(state.bots[0],'m140');assert.equal(client.addHistory(page).bots[0].messages.length,120);});
test('old history and removed bots cannot survive a workspace switch',()=>{const client=new SyncClient();client.apply({full:true,cursor:'a',state:{workspaceId:'one',bots:[{id:'same',messages:[{id:'now'}]}]}});client.addHistory({id:'same',messages:[{id:'old',text:'private'}]});const result=client.apply({full:true,cursor:'b',state:{workspaceId:'two',bots:[{id:'same',messages:[]}]}});assert(!JSON.stringify(result).includes('private'));});
test('API request caps reserve before dispatch; unknown usage and prices remain unknown',t=>{const usage=new Usage({dataRoot:fixture(t)});usage.configure({dailyRequests:2,dailyBudgetUSD:1,rates:[{providerId:'p',model:'m',inputPerMillion:1,outputPerMillion:2}]});const id=usage.beforeRequest({providerId:'p',model:'m'});usage.record(id,{prompt_tokens:100000,completion_tokens:200000});assert.equal(usage.status().today.estimatedUSD,.5);usage.beforeRequest({providerId:'p',model:'other'});assert.equal(usage.status().today.unpricedRequests,1);assert.throws(()=>usage.beforeRequest({providerId:'p',model:'m'}),/request limit/);});
test('browser push rejects arbitrary servers and private network endpoints',()=>{for(const endpoint of ['http://127.0.0.1/push','https://evil.example/push','https://fcm.googleapis.com.evil.example/push','https://web.push.apple.com:444/push'])assert.throws(()=>pushSubscription({endpoint,keys:{}}));});
test('push is paired-device opt-in, encrypted at rest, generic, and revocation stops future dispatch',async t=>{const root=fixture(t),vault=new CredentialVault(root);vault.configure({password});const active=new Set(['phone']),sent=[];const push=new PushNotifications({dataRoot:root,vault,isDeviceActive:id=>active.has(id),send:async(...args)=>sent.push(args)});push.configure({enabled:true});const subscription={endpoint:'https://fcm.googleapis.com/fcm/send/fixture',keys:{auth:Buffer.alloc(16).toString('base64url'),p256dh:Buffer.alloc(65,1).toString('base64url')}};push.subscribe('phone',subscription);assert(!fs.readFileSync(push.file,'utf8').includes(subscription.endpoint));await push.notify({id:'one',kind:'completed',text:'private task details'});assert.equal(sent.length,1);assert(!sent[0][1].includes('private task'));await push.notify({id:'one',kind:'completed'});assert.equal(sent.length,1);active.clear();await push.notify({id:'two',kind:'approval'});assert.equal(sent.length,1);push.close();});
test('catalog imports remain pending and connection recipes never start programs',t=>{const root=fixture(t),store=new Store(root),skills=new Skills({dataRoot:root,store});for(const id of ['hermes-portable','openclaw-portable']){const imported=skills.importSkill(catalogSkill(id));assert(imported);assert.equal(skills.listForBot(store.create({name:id}).id).length,0);}const recipe=catalogRecipe('filesystem',{folder:root});assert.equal(recipe.enabled,false);assert.equal(recipe.allowPackageInstall,false);assert.deepEqual(recipe.botIds,[]);assert(recipe.args.includes('@modelcontextprotocol/server-filesystem@2026.8.31'));});
test('update checks reject draft, preview-by-default and external release URLs',async()=>{const releases=[{draft:false,prerelease:false,tag_name:'v99.0.0',html_url:'https://evil.example'},{draft:false,prerelease:true,tag_name:'v1.0.0',html_url:'https://github.com/Spenz90/folklet/releases/tag/v1.0.0'}];const fetchImpl=async()=>new Response(JSON.stringify(releases));assert.equal((await checkUpdates({current:'0.6.1',fetchImpl})).release,null);assert.equal((await checkUpdates({current:'0.6.1',includePreviews:true,fetchImpl})).release.tag,'v1.0.0');});

test('editing another draft cannot renew an untouched draft and disabling removes stored text',()=>{
 const storage=memoryStorage();let now=1000000000;const draft=new DraftStorage({storage,now:()=>now});draft.bind('workspace');draft.enable(true);
 draft.save({old:'unchanged',active:'first'},{});now+=6*86400000;draft.save({old:'unchanged',active:'edited'},{});now+=2*86400000;
 draft.save({old:'unchanged',active:'edited again'},{});assert.deepEqual(draft.load().drafts,{active:'edited again'});
 draft.enable(false);assert.equal(storage.values.size,0);
});

test('a jump to a source message does not skip the intervening history pages',()=>{
 const bot={id:'sample',messages:Array.from({length:200},(_,i)=>({id:'m'+i,at:i,text:'message '+i})),events:[]},client=new SyncClient();
 client.apply(new StateSync().update({workspaceId:'one',bots:[bot]}));
 client.addHistory(historyPage(bot,null,'m5'));assert.equal(client.before(bot.id),'m140');
 client.addHistory(historyPage(bot,client.before(bot.id)));client.addHistory(historyPage(bot,client.before(bot.id)));
 const messages=client.value().bots[0].messages;assert.equal(messages.length,200);assert.equal(new Set(messages.map(m=>m.id)).size,200);
});

test('restored copies get a new browser scope and cannot inherit push subscriptions',t=>{
 const root=fixture(t),source=path.join(root,'source'),store=new Store(source);
 fs.writeFileSync(path.join(source,'web-push.json'),JSON.stringify({enabled:true,subscriptions:[{deviceId:'old-phone'}]}));
 const target=path.join(root,'restored');restoreBackup(createBackup(source,password),password,target);
 assert.notEqual(new Store(target).db.workspaceId,store.db.workspaceId);
 const push=JSON.parse(fs.readFileSync(path.join(target,'web-push.json')));assert.equal(push.enabled,false);assert.deepEqual(push.subscriptions,[]);
});

test('daily usage limits survive pruning and restarting; repeated usage reports do not double count',t=>{
 const root=fixture(t);let now=Date.UTC(2026,8,8);const usage=new Usage({dataRoot:root,now:()=>now});
 usage.configure({dailyRequests:2,dailyBudgetUSD:10,rates:[{providerId:'p',model:'m',inputPerMillion:1,outputPerMillion:1}]});
 const id=usage.beforeRequest({providerId:'p',model:'m'});usage.record(id,{input_tokens:1000000,output_tokens:1000000});usage.record(id,{input_tokens:1000000,output_tokens:1000000});
 usage.beforeRequest({providerId:'p',model:'m'});usage.state.entries=[];usage.save();
 const restarted=new Usage({dataRoot:root,now:()=>now});assert.equal(restarted.status().today.requests,2);assert.equal(restarted.status().today.estimatedUSD,2);assert.equal(restarted.status().today.unknownUsage,1);assert.throws(()=>restarted.beforeRequest({providerId:'p',model:'m'}),/limit/);
 now+=86400000;assert.equal(restarted.status().today.requests,0);assert.doesNotThrow(()=>restarted.beforeRequest({providerId:'p',model:'m'}));
});

test('scheduled failures back off and cannot throw from the background timer',t=>{
 const root=fixture(t);new Store(root);const vault=new CredentialVault(root);vault.configure({password});let now=Date.UTC(2026,8,8),attempts=0;
 const backups=new Backups({dataRoot:root,vault,isIdle:()=>true,now:()=>now});backups.configure({enabled:true,password});backups.create=()=>{attempts++;throw Error('fixture storage failure');};
 backups.tick();backups.tick();assert.equal(attempts,1);now+=15*60000;backups.tick();assert.equal(attempts,2);assert.match(backups.status().lastError,/15 minutes/);
});

test('publisher signing plans require explicit targets and leave pinned Windows runtimes untouched',t=>{
 const root=fixture(t),identity='a'.repeat(40),timestamp='https://timestamp.example';
 assert.throws(()=>publisherPlan({platform:'win32',identity,timestamp}),/explicit/);
 for(const file of ['desktop/Crew.exe','native/windows-control.exe','runtime/node.exe']){fs.mkdirSync(path.dirname(path.join(root,file)),{recursive:true});fs.writeFileSync(path.join(root,file),'fixture bytes');}
 const plan=publisherPlan({platform:'win32',root,identity,timestamp});assert.equal(plan.length,4);assert(plan.every(step=>!step.args.some(a=>a.endsWith('node.exe'))));assert(plan.some(step=>step.args[0]==='verify'));
 assert.throws(()=>publisherPlan({platform:'win32',root,identity,timestamp:'https://user:password@example.com'}),/timestamp/);
 assert.equal(fs.readFileSync(path.join(root,'desktop/Crew.exe'),'utf8'),'fixture bytes');
});

test('legacy saved connections do not block new session-only connections before vault setup',t=>{
 const root=fixture(t),store=new Store(root),bot=store.create({name:'Sample'});
 new ProviderStore(root).save({type:'openai',apiKey:'old-key',persistKey:true});
 new IntegrationStore({dataRoot:root,store}).save({repo:'example/old',botIds:[bot.id],token:'old-token',persistToken:true});
 new PluginConnections({dataRoot:root,store}).save({name:'Old',type:'mcp',transport:'streamable-http',url:'https://example.com/mcp',token:'old-plugin-token',persistSecrets:true});
 const vault=new CredentialVault(root),providers=new ProviderStore(root,{vault}),integrations=new IntegrationStore({dataRoot:root,store,vault}),plugins=new PluginConnections({dataRoot:root,store,vault});
 assert.equal(providers.save({type:'anthropic',apiKey:'session-key'}).keyStorage,'session');
 assert.equal(integrations.save({repo:'example/new',botIds:[bot.id],token:'session-token'}).tokenStorage,'session');
 assert.equal(plugins.save({name:'New',type:'mcp',transport:'streamable-http',url:'https://example.com/new',token:'session-plugin-token',persistSecrets:false}).secretStorage,'session');
 assert.throws(()=>providers.save({type:'openai',apiKey:'new-key',persistKey:true}),/protection/i);
 assert.throws(()=>integrations.save({repo:'example/private',botIds:[bot.id],token:'new-token',persistToken:true}),/protection/i);
 assert.throws(()=>plugins.save({name:'Blocked',type:'mcp',transport:'streamable-http',url:'https://example.com/blocked',token:'new-token',persistSecrets:true}),/protection/i);
 for(const file of ['provider-secrets.json','integrations.json','plugin-connections.json'])assert(!fs.readFileSync(path.join(root,file),'utf8').includes('session-'));
 vault.configure({password});providers.persist();integrations.persist(integrations.items);plugins.persist(plugins.items);
 for(const file of ['provider-secrets.json','integrations.json','plugin-connections.json'])assert(!fs.readFileSync(path.join(root,file),'utf8').includes('old-'));
});

test('editing protected connections while locked preserves the saved credentials byte for byte',t=>{
 const root=fixture(t),store=new Store(root),vault=new CredentialVault(root);vault.configure({password});
 const plugins=new PluginConnections({dataRoot:root,store,vault}),plugin=plugins.save({name:'Private',type:'mcp',transport:'streamable-http',url:'https://example.com/mcp',token:'private-fixture',persistSecrets:true});
 const telegram=new TelegramNotifications({dataRoot:root,vault});telegram.configure({token:'123456:'+ 't'.repeat(24),persistToken:true});
 const pluginBytes=fs.readFileSync(plugins.file),telegramBytes=fs.readFileSync(telegram.file);vault.close();
 assert.throws(()=>plugins.save({id:plugin.id,name:'Changed'}),/Unlock/);assert.throws(()=>telegram.configure({persistToken:false}),/Unlock/);
 assert.deepEqual(fs.readFileSync(plugins.file),pluginBytes);assert.deepEqual(fs.readFileSync(telegram.file),telegramBytes);
});
