import {escapeReview as esc,reviewLines,reviewSource,reviewUI} from './review-ui-common.mjs';
export function createSkillsUI({api,modal,refresh,getBots,onSource}){
 const {$,show,live,fail,action}=reviewUI({modal});let selected=null;
 const content=revision=>'<p class="note">'+esc(revision.whenToUse)+'</p><h3 class="settings-label">Steps</h3><ol>'+revision.steps.map(step=>'<li>'+esc(step)+'</li>').join('')+'</ol>'+(revision.examples.length?'<h3 class="settings-label">Examples</h3><ul>'+revision.examples.map(example=>'<li>'+esc(example)+'</li>').join('')+'</ul>':'')+'<h3 class="settings-label">Verify the result</h3><ul>'+revision.checklist.map(check=>'<li>'+esc(check)+'</li>').join('')+'</ul>'+reviewSource(revision.source);
 async function open(){
  selected=null;const view=show('Skills','Reusable instructions, reviewed by you.','<div id="skill-library">Loading skills…</div>','skills');
  try{const skills=await api('skills');if(!live(view))return;$('skill-library').innerHTML='<div class="row"><button class="btn primary" data-sk-new>Create a skill</button><button class="btn" data-sk-import>Import JSON</button></div><p class="note">Skills contain instructions and examples. They do not install programs, add tools or grant permissions. New skills and revisions wait for your review.</p>'+(skills.length?'<div class="settings-options">'+skills.map(skill=>{const revision=skill.revisions.find(r=>r.id===skill.activeRevisionId)||skill.revisions.at(-1),pending=skill.revisions.filter(r=>r.status==='pending').length;return '<button class="settings-option" data-sk-open="'+esc(skill.id)+'"><span><b>'+esc(revision.title)+'</b><small>'+(skill.activeRevisionId?'Reviewed':'Draft')+' · '+skill.enabledBotIds.length+' bots'+(pending?' · '+pending+' awaiting review':'')+'</small></span><span>›</span></button>';}).join('')+'</div>':'<p class="empty-box">Save a useful procedure, or ask a bot to propose a skill after completing a task.</p>');}catch(error){if(live(view)){$('skill-library').innerHTML='<button class="btn" data-sk-home>Try again</button>';fail(view,error);}}
 }
 async function detail(id){
  const view=show('Skill','Review instructions and choose which bots can use them.','<div id="skill-detail">Loading skill…</div>','skill-detail');
  try{const skill=await api('skill-get?id='+encodeURIComponent(id));if(!live(view))return;selected=skill;const active=skill.revisions.find(r=>r.id===skill.activeRevisionId),latest=skill.revisions.at(-1),bots=getBots();
   $('skill-detail').innerHTML='<div class="row"><button class="btn" data-sk-home>All skills</button><button class="btn" data-sk-edit="'+esc(id)+'">Draft a revision</button>'+(active?'<button class="btn primary" data-sk-use="'+esc(id)+'">Use now</button><button class="btn" data-sk-export="'+esc(id)+'">Export JSON</button>':'')+'</div><h3>'+esc(active?.title||latest.title)+'</h3>'+(active?content(active):'<p class="note">Review a draft below before activating this skill.</p>')+(active?'<h3 class="settings-label">Available to these bots</h3>'+ (bots.length?bots.map(bot=>'<label class="check"><input type="checkbox" data-sk-enable="'+esc(id)+'" data-sk-bot="'+esc(bot.id)+'" '+(skill.enabledBotIds.includes(bot.id)?'checked':'')+'>'+esc(bot.name)+'</label>').join(''):'<p class="note">Create a bot to enable this skill.</p>'):'')+'<h3 class="settings-label">Revision history</h3><p class="note">Accepting an update changes the instructions used by enabled bots on their next task.</p>'+skill.revisions.slice().reverse().map(revision=>'<details class="learning-card" '+(revision.status==='pending'?'open':'')+'><summary>Revision '+revision.number+' · '+(revision.id===skill.activeRevisionId?'Active':revision.status==='pending'?'Awaiting review':revision.status==='accepted'?'Previously accepted':'Declined')+' · '+esc(revision.title)+'</summary>'+content(revision)+(revision.status==='pending'?'<div class="row"><button class="btn primary" data-sk-accept="'+esc(id)+'" data-sk-revision="'+esc(revision.id)+'">Accept revision</button><button class="btn" data-sk-reject="'+esc(id)+'" data-sk-revision="'+esc(revision.id)+'">Decline</button></div>':'')+'</details>').join('');
  }catch(error){if(live(view)){$('skill-detail').innerHTML='<button class="btn" data-sk-open="'+esc(id)+'">Try again</button>';fail(view,error);}}
 }
 function edit(skill){
  const revision=skill?(skill.revisions.find(r=>r.id===skill.activeRevisionId)||skill.revisions.at(-1)):{title:'',whenToUse:'',steps:[],examples:[],checklist:[]},view=show(skill?'Draft a skill revision':'Create a skill','Save instructions for review before they become active.',`<form id="skill-edit-form"><label for="sk-title">Title</label><input id="sk-title" maxlength="120" required value="${esc(revision.title)}"><label for="sk-when">When to use it</label><textarea id="sk-when" maxlength="2000" required>${esc(revision.whenToUse)}</textarea><label for="sk-steps">Steps — one per line</label><textarea id="sk-steps" rows="7" required>${esc(revision.steps.join('\n'))}</textarea><label for="sk-examples">Examples — one per line</label><textarea id="sk-examples" rows="3">${esc(revision.examples.join('\n'))}</textarea><label for="sk-checks">Verification checklist — one check per line</label><textarea id="sk-checks" rows="3">${esc(revision.checklist.join('\n'))}</textarea><button class="btn primary">Save draft for review</button></form>`,'skill-edit');
  const form=$('skill-edit-form');form.onsubmit=async event=>{event.preventDefault();if(!live(view))return;const body={id:skill?.id,title:$('sk-title').value,whenToUse:$('sk-when').value,steps:reviewLines($('sk-steps').value),examples:reviewLines($('sk-examples').value),checklist:reviewLines($('sk-checks').value)};await action(view,form,()=>api('skill-propose',body),result=>detail(result.skillId));};
 }
 function importForm(){
  const view=show('Import a skill','Import an instruction document as a pending draft.','<form id="skill-import-form"><label for="sk-file">Choose FOLKLET skill JSON</label><input id="sk-file" type="file" accept="application/json,.json"><label for="sk-document">Or paste JSON</label><textarea id="sk-document" rows="12" required maxlength="128000"></textarea><p class="note">Only instruction fields are imported. Sources, bot access and executable files are excluded. Review the draft before accepting it.</p><button class="btn primary">Import for review</button></form>','skill-import');
  const form=$('skill-import-form');let reading=false;
  $('sk-file').onchange=async event=>{const file=event.target.files?.[0];if(!file||reading)return;reading=true;try{await action(view,form,async()=>{if(file.size>128000)throw Error('Choose a JSON document under 128 KB.');return file.text();},value=>{$('sk-document').value=value;});}finally{reading=false;}};
  form.onsubmit=async event=>{event.preventDefault();if(!live(view)||reading)return;const document=$('sk-document').value;await action(view,form,()=>api('skill-import',{document}),result=>detail(result.skillId));};
 }
 function useForm(skill){
  const bots=getBots(),view=show('Use this skill now','This queues one task; it does not change a bot’s enabled skills.','<form id="skill-use-form"><label for="sk-use-bot">Bot</label><select id="sk-use-bot" required>'+bots.map(bot=>'<option value="'+esc(bot.id)+'">'+esc(bot.name)+'</option>').join('')+'</select><label for="sk-task">What should this task do?</label><textarea id="sk-task" rows="5" maxlength="20000" required></textarea><button class="btn primary" '+(bots.length?'':'disabled')+'>Start task</button>'+(bots.length?'':'<p class="note">Create a bot first.</p>')+'</form>','skill-use');
  const form=$('skill-use-form');form.onsubmit=async event=>{event.preventDefault();if(!live(view))return;const body={id:skill.id,botId:$('sk-use-bot').value,instruction:$('sk-task').value};await action(view,form,()=>api('skill-use',body),async result=>{await refresh();if(!live(view))return;const task=result.task||result,source={botId:body.botId,taskId:task.id};if(onSource&&task.id){$('modal').close();onSource('/?bot='+encodeURIComponent(body.botId)+'&task='+encodeURIComponent(task.id));}else show('Task queued','Your bot will use the reviewed skill.','<p class="note">The task has been added to its queue.</p>'+reviewSource(source),'skill-queued');});};
 }
 document.addEventListener('change',async event=>{const d=event.target.dataset;if(!d?.skEnable)return;const checkbox=event.target,enabled=checkbox.checked,view=$('modal-error'),scope=$('skill-detail');const success=await action(view,scope,()=>api('skill-enable',{id:d.skEnable,botId:d.skBot,enabled}),()=>detail(d.skEnable));if(!success)checkbox.checked=!enabled;});
 document.addEventListener('click',async event=>{const d=event.target.closest('button')?.dataset;if(!d)return;const view=$('modal-error');try{
  if(d.skHome!==undefined)await open();else if(d.skOpen)await detail(d.skOpen);else if(d.skNew!==undefined)edit();else if(d.skImport!==undefined)importForm();
  else if(d.skEdit&&selected?.id===d.skEdit)edit(selected);else if(d.skUse&&selected?.id===d.skUse)useForm(selected);
  else if(d.skAccept||d.skReject){const id=d.skAccept||d.skReject;await action(view,$('skill-detail'),()=>api(d.skAccept?'skill-accept':'skill-reject',{id,revisionId:d.skRevision}),()=>detail(id));}
  else if(d.skExport)await action(view,$('skill-detail'),()=>api('skill-export?id='+encodeURIComponent(d.skExport)),value=>{const url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='crew-skill.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
 }catch(error){fail(view,error);}});
 return {open,detail};
}
