import fs from 'node:fs';import path from 'node:path';import {spawnSync} from 'node:child_process';import {fileURLToPath} from 'node:url';
import {macSigningPlan} from './Sign-Mac.mjs';
import {assertNoLinks} from './Build-Unix.mjs';
export function publisherPlan({platform=process.platform,root,identity,timestamp,notaryProfile}={}){
 if(typeof root!=='string'||!root.trim())throw Error('Choose an explicit extracted release directory or Mac app with --root.');root=path.resolve(root);assertNoLinks(root);if(!fs.statSync(root).isDirectory())throw Error('Choose an extracted release directory or Mac app.');
 if(platform==='win32'){if(!/^[a-f\d]{40}$/i.test(identity||''))throw Error('Supply the public SHA-1 thumbprint of your installed publisher certificate.');let url;try{url=new URL(timestamp);}catch{throw Error('Supply your publisher’s RFC3161 timestamp URL.');}if(!['http:','https:'].includes(url.protocol)||url.username||url.password||url.hash)throw Error('Invalid timestamp URL.');return ['desktop/Crew.exe','native/windows-control.exe'].flatMap(relative=>{const file=path.join(root,relative);assertNoLinks(file);const stat=fs.statSync(file);if(!stat.isFile()||stat.nlink!==1)throw Error('Signing targets must be regular files.');return [{command:'signtool.exe',args:['sign','/sha1',identity,'/fd','SHA256','/tr',url.href,'/td','SHA256','/d','Folklet',file]},{command:'signtool.exe',args:['verify','/pa','/all',file]}];});}
 if(platform==='darwin'){if(!/^Developer ID Application: .+\([A-Z0-9]{10}\)$/.test(identity||''))throw Error('Supply your installed Developer ID Application identity.');if(!root.endsWith('.app'))throw Error('Choose the extracted Folklet.app.');const plan=macSigningPlan(root).map(target=>({command:'/usr/bin/codesign',args:['--force','--sign',identity,'--timestamp','--options','runtime','--preserve-metadata=entitlements,requirements',target]}));plan.push({command:'/usr/bin/codesign',args:['--verify','--deep','--strict',root]});if(notaryProfile){if(!/^[A-Za-z0-9_.-]{1,80}$/.test(notaryProfile))throw Error('Use a simple existing notary keychain-profile name.');const archive=root+'.notarization.zip';if(fs.existsSync(archive))throw Error('Move the previous notarization submission archive before running again.');plan.push({command:'/usr/bin/ditto',args:['-c','-k','--keepParent',root,archive]},{command:'/usr/bin/xcrun',args:['notarytool','submit',archive,'--keychain-profile',notaryProfile,'--wait']},{command:'/usr/bin/xcrun',args:['stapler','staple',root]},{command:'/usr/bin/xcrun',args:['stapler','validate',root]},{command:'/usr/sbin/spctl',args:['--assess','--type','execute','--verbose',root]});}return plan;}
 throw Error('Publisher signing is supported on the matching Windows or Mac host.');
}
if(process.argv[1]&&path.resolve(process.argv[1])===fileURLToPath(import.meta.url))try{const args=process.argv.slice(2),apply=args.includes('--apply');const fields=args.filter(a=>a!=='--apply');if(fields.length%2)throw Error('Use --root PATH --identity ID [--timestamp URL] [--notary-profile NAME] [--apply].');const values={};for(let i=0;i<fields.length;i+=2){if(!['--root','--identity','--timestamp','--notary-profile'].includes(fields[i]))throw Error('Unknown signing option.');values[fields[i].slice(2)]=fields[i+1];}const plan=publisherPlan({root:values.root,identity:values.identity,timestamp:values.timestamp,notaryProfile:values['notary-profile']});if(!apply)console.log(JSON.stringify({mode:'review',commands:plan},null,2));else{for(const step of plan){const result=spawnSync(step.command,step.args,{stdio:'inherit',shell:false,windowsHide:true,timeout:600000});if(result.error||result.status!==0)throw Error('Publisher signing or verification failed. Do not distribute this output.');}console.log('Signing steps passed. Repackage, regenerate checksums and run the release checks on this signed output.');}}catch(error){console.error(error.message);process.exitCode=1;}
